### ISSUE TITLE
False Positive `UPnP` should be `On`

### ISSUE THREAD

**Issue by xavier2k6** [crate-ci/typos#1001]
typos 1.20.9

`UPnP` is an abbreviation for [Universal Plug and Play](https://en.wikipedia.org/wiki/Universal_Plug_and_Play)

![Screenshot 2024-04-17 183925](https://github.com/crate-ci/typos/assets/42386382/091cd2c0-a746-4960-9d2a-85ec421896e3)

**Comment by epage** [comment]
The root cause is the same as #1002 and closing in favor of that as I've already commented on it
