### ISSUE TITLE
Interactive UI for accepting typo corrections and other ideas

### ISSUE THREAD

**Issue by cmdcolin** [crate-ci/typos#1015]
This could be outside the scope of the repo but i had some ideas for add-on features that could benefit from a sort of "interactive UI"

It would be interesting to have a couple of features that could be categorized as "interactive UI for accepting hits"

- interactive UI for accepting hits one by one with accept/ignore/"turbo ignore" (add the current term to _typos.toml ignore list :))
- interactive UI for bulk accepting all instances of a certain typo 

potentially, an external tool could leverage something like --format json or use the `typos` crate to make this type of 'higher level' tool. potentially could leverage things like fzf or something like that too to make the ui slick and searchable. just an idea. if anything like this already exists let me know!

**Comment by epage** [comment]
Thanks for your input!  To consolidate the conversation, I'm going to close in favor of #397.  If there is a reason to keep this open separately, let us know!

**Comment by cmdcolin** [comment]
no worries that is fine!
