### ISSUE TITLE
v1.22.1 release not published to pypi?

### ISSUE THREAD

**Issue by aaravind100** [crate-ci/typos#1027]
The v1.22.1 release is not published to pypi.

I also noticed [this](https://github.com/crate-ci/typos/actions/runs/9390245957) workflow has failed.

**Comment by odinho** [comment]
Was going to post about the NPM release being at `1.16.23` (half a year old). I was running with this locally, but the one I'll add to all developer machines it's convenient to use a regular npm package, would be nice to bump the version number. I didn't find where that was done in this repo.

**Comment by aaravind100** [comment]
> Was going to post about the NPM release being at `1.16.23` (half a year old) - but I'll just comment here.
> 
> I was running `typos` locally, but the one I'll add to all developer machines it's convenient to use a regular npm package, would be nice to bump the version number. I didn't find where that was done in this repo.

I run typos via pre-commit, so when updating the config as per the [docs](https://github.com/crate-ci/typos/blob/master/docs/pre-commit.md#pre-commit) to v1.22.1, pre-commit this gives this error.
```
ERROR: No matching distribution found for typos==1.22.1
```
That how I checked pypi :)

1.22.0 works btw.

**Comment by epage** [comment]
The npm packages were done by a third party. The reason for PyPI packages is to make pre-commit nicerd

**Comment by epage** [comment]
Looks like we hit a timeout
https://github.com/crate-ci/typos/actions/runs/9390245957/job/25859623493#step:3:1

The following test-run in `main` succeeded so it seems to be a one off. A new release hopefully will work. Will get to that in a couple hours.

**Comment by epage** [comment]
122.2 seems to be up https://pypi.org/project/typos/1.22.2/

**Comment by aaravind100** [comment]
> 122.2 seems to be up https://pypi.org/project/typos/1.22.2/

Thank you!!

Can confirm it works.
