### ISSUE TITLE
False positive `arbitral`

### ISSUE THREAD

**Issue by tfiedlerdejanze** [crate-ci/typos#1028]
Typos currently corrects `arbitral -> arbitrary`

https://en.wiktionary.org/wiki/arbitral

**Comment by epage** [comment]
Thanks for reporting this!

We pulled in the OpenOffice dictionaries to try to catch cases like this.  I know we aren't handling their suffixes correctly so we have fewer words than we should but I'm not even seeing how that word can be made from their dictionary and yet LibreOffice is able to correct it.
