### ISSUE TITLE
false positive for preEmptedState

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#1054]
This may be wrong.
`preEmptedState -> preEmptiedState`

premet is a verb
https://www.merriam-webster.com/dictionary/preempt

**Comment by epage** [comment]
Shouldn't that be `preEmptedState` -> `preemptedState`.  https://www.merriam-webster.com/dictionary/preempt isn't showing it as hyphenated which is the only reason I would expect it to be `preEmpt` rather than `preempt`
