### ISSUE TITLE
how to ignore a word in a context

### ISSUE THREAD

**Issue by ccoVeille** [crate-ci/typos#1056]
I have code with the following words: CC-BY-ND, or ND-JSON

Typos detects the ND as invalid because it expects AND, and it would be a normal typo if I was writing:

```
My favorite ice cream flavors are chocolate ND strawberry
```

but here CC-BY-ND, or ND-JSON are valid usage of ND

I had to exclude "ND", but it means I can no longer detect "chocolate ND strawberry"

I tried this

```toml
[default.extend-words]
CC-BY-ND = "CC-BY-ND"
ND-JSON = "ND-JSON"
```

and later a regexp

```toml
[default]
extend-ignore-identifiers-re = [
    "ND.JSON",
    "CC.BY.ND"
]
```

the ignore rules seems to catch only the word, not the context surrounding the word

 I'm lucky because it's case-sensitive. I'm not likely to face ND in a text, and this would be detected

```
My favorite ice cream flavors are chocolate nd strawberry
```

But I would like to know there is something I could do about this

**Comment by epage** [comment]
> the ignore rules seems to catch only the word, not the context surrounding the word

This is a variant of #743 and #745.  We consider "words" to be elements of an identifier.  We only recognize identifiers with `_` and not `-`

What can work for your is `default.extend-ignore-re` which accepts arbitrary regexes.  Anything appearing within those regexes will be ignored.

**Comment by ccoVeille** [comment]
Thanks. I was indeed using `extend-ignore-identifiers-re` not `extend-ignore-re`

Problem solved, thanks
