### ISSUE TITLE
False positive in JWTs

### ISSUE THREAD

**Issue by hauleth** [crate-ci/typos#1057]
It complains about `Nd` in this piece of text:

```
error: `Nd` should be `And`
  --> ./docs/development/setup.md:107:181
    |
107 |   --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1MTkyODI0LCJleHAiOjE5NjA3Njg4MjR9.M9jrxyvPLkUxWgOYSf5dNdJ8v_eRrq810ShFRT8N-6M'
    |                                                                                                                                                                                     ^^
    |
```

I have filtered out all JWTs using this regex:

```
\bey[A-Za-z0-9_-]{20,}\.ey[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\b
```

As per spec *all* JWTs must have `ey` as beginning of 1st and 2nd segment (as `printf '{"' | base64` results in `eyI=`, we cannot check for `eyI` as `I` can change depending on further parts of message), but still - JWT prevalence would make me think, that it will be handled by default.

**Comment by epage** [comment]
JWT seem common enough and look specific enough that we could support them by default, like hex colors, urls, etc.
