### ISSUE TITLE
Allow config in Cargo.toml

### ISSUE THREAD

**Issue by alerque** [crate-ci/typos#1060]
The Cargo manifest `Cargo.toml` can be used for 3rd party tooling configuration, (e.g. as done by [`git cliff`](https://git-cliff.org/docs/integration/rust), etc.) in a `[package.metadata.X]` key space. I see Typos supports something similar for `pyproject.toml`, but it for Rust-only projects it would be nice to get the same thing for Typos configuration data in `Cargo.toml`.

**Comment by epage** [comment]
pyproject.toml was added in #790 and its reasonable to support Cargo.toml as well.
