### ISSUE TITLE
Please do a v1 tag

### ISSUE THREAD

**Issue by ondrejmirtes** [crate-ci/typos#1067]
Hi, I'd love to use your action but it's a bit wearing to need to update the patch version every week after release in my .yml workflow files.

What other GitHub Actions typically do is that they make a `v1` tag and the tag is continuously updated to point to the latest patch release in `1.*`. That way I can just use `@v1` in my workflow file and will always have the latest v1 release.

Thank you for considering.

**Comment by epage** [comment]
Is an update bot, set to a cadence of your preference, also workable?  That would that CI doesn't suddenly start failing because a new correction was added.
