### ISSUE TITLE
[question] locale en_us not working

### ISSUE THREAD

**Issue by eismont21** [crate-ci/typos#1081]
I've set the locale to en_us to correct to American English, but it doesn't seem to work. I tested with word pairs like _color/colour_ and _organize/organise_, but both versions were accepted (no errors). What do I need to change to strictly follow the US dialect? 

`_typos.toml`
```
[default]
default.locale = "en_us"
extend-ignore-identifiers-re = [
    "ba", # Part of Jypyter notebook cell identifiers. Issue: https://github.com/crate-ci/typos/issues/415
]
check-filename = true

[default.extend-words]
arange = "arange"  # e.g. `numpy.arange`

[files]
ignore-hidden = false
extend-exclude = [".git/"] # e.g. git directory
```

**Comment by epage** [comment]
There are two parts to this

The config isn't correct:
```diff
[default]
-default.locale = "en_us"
+locale = "en-us"
```

We had a bug which is fixed in #1082 and released in v1.23.7

**Comment by eismont21** [comment]
Thanks. It works now. However, with this locate, I have encountered a false positive: _it goes_ -> _it ges_

**Comment by epage** [comment]
We get our data from varcon.  Looks like we had an old copy of varcon (#1084) but that still didn't address that entry.    In #1086, I decided to filter out unverified varcon entries which includes the `goes -> ges` entry so this should now be fixed
