### ISSUE TITLE
feat:check a few specific directories only

### ISSUE THREAD

**Issue by detailyang** [crate-ci/typos#1099]
In our scenario, we only want to check a few specific directories. How should we implement this?

**Comment by epage** [comment]
We have `files.extend-exclude`.  It uses gitignore glob syntax.  iirc that means you can do
```
*
!some-dir/
```

**Comment by detailyang** [comment]
Many thinks :)

**Comment by detailyang** [comment]
I'm testing this, it looks like ignore all files:(.

```
typos --version
typos-cli 1.24.5
```

```
typos --dump-config /dev/stdout
[files]
extend-exclude = [
    "*",
    "!test/",
]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true
```

> We have `files.extend-exclude`. It uses gitignore glob syntax. iirc that means you can do
> 
> ```
> *
> !some-dir/
> ```

@epage

**Comment by detailyang** [comment]
@epage Could you please take another look? It's still not working for me. I only want to check a specific directory. Thanks :)


```
detailyang@Docker-dev:~/work/test/d$ typos --version
typos-cli 1.28.3
``

```bash
mkdir test
cd test
mkdir -p {a,b,c}/tests; touch {a,b,c}/tests/file
cat <<EOS > .typos.toml
detailyang@Docker-dev:~/work/test/d$ typos --version
typos-cli 1.28.3
EOS
typos . --files
```

**Comment by epage** [comment]
For some reason, I have to do
```toml
[files]
extend-exclude = ["*", "!c", "!c/**"]
```

Going to try to double check if thats specific to typos, the format, and if there is a way to improve that.

**Comment by epage** [comment]
It appears `.gitignore` requires both as well.

**Comment by detailyang** [comment]
> For some reason, I have to do出于某种原因，我必须这样做
> 
> ```toml
> [files]
> extend-exclude = ["*", "!c", "!c/**"]
> ```
> 
> Going to try to double check if thats specific to typos, the format, and if there is a way to improve that.尝试仔细检查这是否特定于拼写错误、格式，以及是否有办法改进它。

Thanks. Anyway it works :)
