### ISSUE TITLE
False positive: Behaviour -> Behavior

### ISSUE THREAD

**Issue by arvid-norlander** [crate-ci/typos#1109]
Behaviour is the correct British spelling, and it is extremely opinionated to suggest switching to the American spelling.

This seems to have been introduced somewhere between 1.23.2 and 1.25.0 (which is what our renovate workflow is trying to update for pre-commit).

**Comment by epage** [comment]
I put "Behaviour" in a  file and ran typos on it and got no corrections.  Could you provide more complete reproduction steps?

**Comment by arvid-norlander** [comment]
Ah seems our locale was incorrectly set to en-us and no one noticed before. My bad.
