### ISSUE TITLE
Request: Ignore files when used with lint-staged

### ISSUE THREAD

**Issue by bmulholland** [crate-ci/typos#1110]
(Thanks for this project, it's fantastic!)

I'm ignoring machine-generated files in my typos config, though some of them are checked into git. This is working well: running typos doesn't show an error in those files.

I use lint-staged to check for typos on files before commit. This means that typos-cli gets the generated files passed in as an explicit argument. It appears that directly passing in a file overrides `extend-exclude`, so these frequently error out. I think that's generally the correct choice, but for this use-case, I need a way to force the exclude to take priority. (There's no way to have lint-staged understand which files typos ignores and avoid passing them through.)

ESLint has `--no-warn-ignored` to this use-case. Would this project consider something similar?

**Comment by epage** [comment]
You are looking for `--force-exclude`

**Comment by bmulholland** [comment]
Oh awesome. I'd checked the config options, not the CLI flags. Thanks!
