### ISSUE TITLE
Check for `via.` -> `via`

### ISSUE THREAD

**Issue by madsmtm** [crate-ci/typos#1113]
Not a native speaker, I learned today that "via" is a word, and not an abbreviation.

Would it make sense for `typos` to check for usage of `via.`, and suggest `via` instead?

One fear with checking for the full stop `.` would be that it might inadvertently catch sentence separators, but I don't think that's the case here, all grammatically correct instances of "via" would want to have a word afterwards?

**Comment by MarijnS95** [comment]
Sounds good. I'd say that if `via` would be used at the end of a sentence, the "synonym" `through` is used instead.

**Comment by epage** [comment]
Typos does not know what grammar it is operating in when it is correcting identifiers and words, whether it be COBOL or English.  As such, we cannot make punctuation corrections.
