### ISSUE TITLE
Unable to specify capitalised existing word in default.extend-words

### ISSUE THREAD

**Issue by sorrison** [crate-ci/typos#1122]
We have an acronym "FoR" that we use.

I've set:

```
[default.extend-words]
FoR = "FoR"
```

However this doesn't seem to take any affect. I think it's because it's a capitalised version of "for" ?

I can add
`Fo = "Fo" `

to fix it but it doesn't seem like the right approach here?

```
error: `Fo` should be `Of`, `For`, `Do`, `Go`, `To`
  --> nectar_dashboard/rcallocation/templates/rcallocation/_form_resources.html:226:61
    |
226 |                                     <li>I have provided the FoR code to describe the research for this project.</li>
    |                                                             ^^
    |
```

**Comment by epage** [comment]
In typos, "words" are case insenasitive.  We only handle case as part of "identifiers".  

For the case you gave, you can do
```toml
[default.extend-identifiers]
FoR = "FoR"
```

**Comment by sorrison** [comment]
Ahh yes, I think I had added it to extend-words and extend-identifiers and it wasn't working but just adding it to identifiers works great, thanks
