### ISSUE TITLE
Question: Define false positives in a separate file

### ISSUE THREAD

**Issue by jvacek** [crate-ci/typos#1128]
I'd like to have one list of false positives that I use in all my repos.

It would be nice if I can either "extend" the configuration form another file, or define specifically the words I want to mark as false positives in some format that typos would pick up from

CSpell does this with custom dictionaries which is just a text file, where each word is a list. Would be nice to have something similar which I can easily share

**Comment by epage** [comment]
This is being discussed in #931 and closing in favor of that. If there is a reason to keep this open, let us know.
