### ISSUE TITLE
Why is "Heigfht' not marked as typo?

### ISSUE THREAD

**Issue by dyollb** [crate-ci/typos#1130]
I recently noticed that `Heigfht` is not corrected. I tested with our own `_typos.toml` config and with the default config.

The typo was in a .cpp file. It is reproducible, e.g. by adding following line to a .cpp file.
```cpp
auto Heigfht = "Heigfht";
```

I am using typos `v1.26.0`.

If I run `typos --words` (or `typos --identifiers`) I see the word in the output. But it would be interesting to understand why it is not marked as a spelling mistake.

**Comment by epage** [comment]
See our [FAQ](https://github.com/crate-ci/typos?tab=readme-ov-file#faq)
