### ISSUE TITLE
typos Package Not Found v1.26.6 in CI Workflow

### ISSUE THREAD

**Issue by Maricaya** [crate-ci/typos#1135]
During a CI pipeline run, the step for installing the typos package fails with a 404 error. The CI is attempting to download the typos binary from GitHub releases, but it encounters a "404 Not Found" error when trying to download the specific version (v1.26.6).

https://github.com/databendlabs/bendsql/actions/runs/11504244384/job/32023321366?pr=486

**Comment by epage** [comment]
Closing in favor of #1134
