### ISSUE TITLE
Incorrect fix: alingments->alinements

### ISSUE THREAD

**Issue by cmdcolin** [crate-ci/typos#1143]
alingments is currently being corrected to alinements but it should be alignments

```
error: `alingments` should be `alinements`
  --> ./test.txt:1:1
  |
1 | alingments
  | ^^^^^^^^^^
  |

```

**Comment by epage** [comment]
Hmm, this is an interesting case.  We try to keep our dictionary agnostic of english dialects by correcting to the closest variant of a word and then switching that to a specific dialect if requested.

varcon has this entry
```
# alignment <verified> (level 20)
A B: alignment / AV: alinement
A B: alignments / AV: alinements
A B: alignment's / AV: alinement's
```
Regarding `level 20`

>  The levels generally mean the following:
>   <= 35: Very common word
>   <= 70: Can be found in the dictionary
>      80: Likely a valid word, can likely be found in an
>          unabridged dictionary
>    > 80: May not even be a legal word

> As of version 5.0, most
clusters with headwords in common usage (SCOWL level 35 and below)
should now be checked, as well as many others. 

Regarding `<verified>`

> Earlier versions of varcon contained numerous errors.  With version
5.0 massive effort has been made to correct many of these errors.
Clusters that have undergone some form of verification (and likely
correction) are marked with "<verified>". 

As for `AV`

> A: American

> V: seldom used variant

However, visually, I see that `alignment` is closer than `alinement` to the users intent *but* for some reason our word similarity check is saying `alinement` is a better fit (a letter replacement vs a letter swap).  I'll have to check their scores more directly and see if there is any automated tweaking to be made or if I'll have to hack this.

**Comment by epage** [comment]
Huh, looks like we ran into this with `alinging` and put a hack in.  Doing the same.
