### ISSUE TITLE
false positive in go.sum

### ISSUE THREAD

**Issue by yokonao** [crate-ci/typos#1158]
typos-cli 1.28.0 seems to no longer ignore go.sum unlike <= 1.27.3.
So, the latest typos-cli found a false positive typo in our project.

https://github.com/crate-ci/typos/pull/1155/files#diff-62ff510ab44e0f05e6fe71d32cbfeac6a05c5a4d3087ec0c2599937f268bb9f2L145-R163
The cause seems to be that go.sum was excluded from the list of lock files in the above PR.

Thank you for your efforts!

**Comment by CNSeniorious000** [comment]
The same for `pnpm-lock.yaml`

**Comment by epage** [comment]
Thanks for reporting this!  Looked over the changes a couple of times and still missed this bad sync from `ignore`.
