### ISSUE TITLE
False positive: parametriz* -> parameteriz*

### ISSUE THREAD

**Issue by mlegner** [crate-ci/typos#1164]
#1157 added two corrections:

```
parametrizations,parameterizations
parametrized,parameterized
```

However, Many dictionaries accept "parametrize" as a valid form next to "parameterize" ([Merriam-Webster](https://www.merriam-webster.com/dictionary/parameterize), [The Free Dictionary](https://www.thefreedictionary.com/parametrize)), it is used by [Wikipedia](https://en.wikipedia.org/wiki/Parametrization) as the default, and the [Google trends](https://trends.google.com/trends/explore?date=all&q=parametrize,parameterize&hl=en-US) are around 50:50.

IMHO, these should be removed again.

**Comment by epage** [comment]
Interesting, [varcon](http://wordlist.aspell.net/varcon/) doesn't consider these variants of each other and we didn't block this from going in for being in varcon because the related entries are not verified.

**Comment by mlegner** [comment]
Thank you so much for the quick fix, @epage! 🙏
