### ISSUE TITLE
Snake case apparently isn't tokenized

### ISSUE THREAD

**Issue by neugartf** [crate-ci/typos#1168]
Hey! Thanks for the awesome tool! 

Just stumbled over a case in our xml's (`android:layout_height="@dimen/bottomsheet_hanlde_hight"`), where the `handle` and `hight` wouldn't be tokenized and thus not corrected (?).

Seeing the test `tokenize_underscore_doesnt_separate` I wonder if that is on purpose and how to fix this for our use case?
Thank you!

---
Added test to check this scenario 
```rust
    #[test]
    fn tokenize_underscore_separate() {
        let parser = Tokenizer::new();

        let input = "bottomsheet_hanlde_hight";
        let actual: Vec<_> = parser.parse_bytes(input.as_bytes()).collect();
        assert_data_eq!(
            actual.to_debug(),
            str![[r#"
[
    Identifier {
        token: "bottomsheet",
        case: None,
        offset: 0,
    }, Identifier {
        token: "hanlde",
        case: None,
        offset: 12,
    },
     Identifier {
        token: "hight",
        case: None,
        offset: 19,
    },
]

"#]]
        );

    }
    
   ```

Test result
   ```    
    ---- expected: src/tokens.rs:1222:13
++++ actual:   In-memory
   1    1 | [
   2    2 |     Identifier {
   3      -         token: "bottomsheet",
        3 +         token: "bottomsheet_hanlde_hight",
   4    4 |         case: None,
   5    5 |         offset: 0,
   6      -     }, Identifier {
   7      -         token: "hanlde",
   8      -         case: None,
   9      -         offset: 12,
  10      -     },
  11      -      Identifier {
  12      -         token: "hight",
  13      -         case: None,
  14      -         offset: 19,
  15    6 |     },
  16    7 | ]


 ```

**Comment by epage** [comment]
Note that the `Tokenizer` returns `Identifier`s which is an attempt to match the common definition of an identifier across languages.  We spell check these against a list of identifier typos.  We then call [`Identifier::split`](https://docs.rs/typos/latest/typos/tokens/struct.Identifier.html#method.split) to then spell check `Word`s against a list of word typos.

You can see this in action with the debug flags `--identifiers` and `--words`
```console
$ echo bottomsheet_hanlde_hight | typos - --identifiers
bottomsheet_hanlde_hight

$ echo bottomsheet_hanlde_hight | typos - --words
bottomsheet
hanlde
hight
```

This is covered in our [FAQ](https://github.com/crate-ci/typos?tab=readme-ov-file#why-was--not-corrected)

**Comment by neugartf** [comment]
Thanks for checking :)!

Have you tried with the example also? Because in this case the value gets kind of lost.

```bash
$ echo 'android:layout_height="@dimen/bottomsheet_hanlde_hight"' | typos - --identifiers
android
layout_height

$ echo 'android:layout_height="@dimen/bottomsheet_hanlde_hight"' | typos - --words
android
layout
height

```

**Comment by epage** [comment]
From that faq entry:

> Does the identifier show up in typos --identifiers or the word show up in typos --words? If not, it might be subject to one of typos' heuristics for detecting non-words (like hashes) or unambiguous words (like words after a \ escape).

My guess is that last part looks too much like  url.

**Comment by neugartf** [comment]
Sounds spot on. Would you mind if I try to fix this behaviour?

**Comment by epage** [comment]
That depends on the fix.  If we stop correctly detecting URLs, that may negatively affect other people.

**Comment by neugartf** [comment]
I tried to implement this, but my rust skills are far too non-existent that it makes sense to pursue this. I specifically failed to detect whole words (like "http") with the winnow library (to be able to detect URLs better).
If anyone else want's to take this, go ahead. Otherwise feel free to close this 🥲.
