### ISSUE TITLE
[FR]: I would ask for support installation through the pip package?

### ISSUE THREAD

**Issue by chriss1245** [crate-ci/typos#1170]
Hi, I discover this wonderful tool recently.  Actually I was looking for something similar a lot of time ago. I never found one which seems okay. This one seems so. But I need to install it though the pip module. I wonder whether  is it possible to upload it to pypi. Thanks a lot.

**Comment by epage** [comment]
See https://pypi.org/project/typos/

We primarily support it for pre-commit

**Comment by chriss1245** [comment]
Sounds good to me
