### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by hardliner66** [crate-ci/typos#258]
I just tried to run the tool on all our sources and it crashed. Here is the crash report:
[report.tar.gz](https://github.com/crate-ci/typos/files/6553972/report.tar.gz)

This is the file that makes it crash:
[bad_file.tar.gz](https://github.com/crate-ci/typos/files/6553993/bad_file.tar.gz)

**Comment by epage** [comment]
Thanks for reporting this!

I had thought I had gotten all of the unicode handling correct but apparently I am missing something.  I'll dig into this.

**Comment by epage** [comment]
`.get(slice).unwrap()` should just be `&line[slice]` to get a good message
```
thread 'main' panicked at 'byte index 28 is not a char boundary; it is inside '�' (bytes 26..29) of `SetupFileMissing=In�tala�n� adres�r neobsahuje s�bor %1. Opravte, pros�m, t�to chybu alebo si zaobstarajte nov� k�piu tohto produktu.`', src/bin/typos-cli/report.rs:194:63
```
Need to dig into the unicode meaning for this.  It looks like `\xFD a` is one character and we are trying to slice right before the `a`.  If I can confirm this, it means something isn't right in our parser, it isn't correctly identifying unicode boundaries when identifying words.

**Comment by epage** [comment]
Found the problem and got a fix running through CI now!

Thanks again for trying `typos` and for reporting this issue!

**Comment by epage** [comment]
v1.0.2 is now released with the fix for this.  Given time, pre-built binaries will get uploaded.

I'm also writing up a guide that explains how to exempt words and files.

**Comment by hardliner66** [comment]
Nice. I just ran the tool again and it didn't crash. Thanks a lot.
