### ISSUE TITLE
line numbers are off

### ISSUE THREAD

**Issue by steven807** [crate-ci/typos#259]
Nifty!  But errors after the first (even across files) seem to be listed on the wrong line numbers -- they are earlier than reported.
(Sorry, I don't have a reproducible case. But when I ran it on a code base, I found this immediately.)

**Comment by epage** [comment]
Thanks for reporting this!

I was able to reproduce it.  The first couple of cases I checked were off by 1 but after enough cases, I found one off by 3.  Mostly noticing this so I don't forget and look in the wrong place

**Comment by epage** [comment]
It looks like we start off by 1 line and then increase by 1 for each new typo found.

**Comment by epage** [comment]
v1.0.1 is now published with this fix.  Pre-built binaries will be uploaded to Github as the CI gets to them
