### ISSUE TITLE
Stable otuput

### ISSUE THREAD

**Issue by msiebuhr** [crate-ci/typos#266]
I like fixing things by doing `watch <tool>`, but when running `watch typos` the output jumps around, making it very difficult to keep track of what one should edit.

I'm guessing directories are being traversed in random order, and that a well-placed `sort()` should fix it.

**Comment by epage** [comment]
So I don't use `watch` but I assume what you need is data returned segregated by file, rather than interleaved.  This can be accomplished by passing `-j1`.  If sorting is needed, that can be added as well.

**Comment by epage** [comment]
Assuming this is resolved.  Feel free to speak up if it isn't
