### ISSUE TITLE
Don't Change Typos inside of URL

### ISSUE THREAD

**Issue by Skylion007** [crate-ci/typos#288]
I tried to apply this automatically to some repos and it tried to fix some URLs. Obviously, that won't work if the original URL has a typo and the URL is not under your control. Absolute HTTPS URLs should not be changed or at least there should be an option to disable the changing of them.

**Comment by epage** [comment]
Things that might be useful from another tool
- email handling: https://github.com/client9/misspell/blob/master/notwords.go#L66
- host handling: https://github.com/client9/misspell/blob/master/notwords.go#L71
- escape sequences: https://github.com/client9/misspell/blob/master/notwords.go#L77
- urls: https://github.com/client9/misspell/blob/master/url.go

**Comment by Skylion007** [comment]
RFC 5322 <http://www.ietf.org/rfc/rfc5322.txt> ie: http://emailregex.com/
exists

**Comment by Skylion007** [comment]
Even worse, I found it mangles go get urls for people who have intentional typos in their usernames. This breaks the repo. Furthermore, that regex won't catch it. Here is a diff in a go repo I tried this on.
```
-       "github.com/Unknwon/goconfig"
+       "github.com/Unknown/goconfig"
```
