### ISSUE TITLE
Don't get confused by c-escape characters

### ISSUE THREAD

**Issue by epage** [crate-ci/typos#3]
Scspell will parse the file assumng escape characters exist but let you opt out.
See https://github.com/myint/scspell/blob/master/scspell/__init__.py#L78

Escape character support could instead be a file type setting, like dictionary values

**Comment by epage** [comment]
Before we support this, we'll probably want a way to define file types and what traits those file types should have (specialized dictionaries, `_` / `-` as identifier characters, and whether escape sequences are supported.

That can then be extended into a config file that works with custom dictionaries (#9) to allow the user to override existing file type definitions or add their own.

**Comment by epage** [comment]
C++'s grammar rules: https://en.cppreference.com/w/cpp/language/escape

scspell's regex:
```python
# Treat anything alphanumeric as a token of interest, as long as it is not
# immediately preceded by a single backslash.  (The string "\ntext" should
# match on "text" rather than "ntext".)
C_ESCAPE_TOKEN_REGEX = re.compile(r'(?<![^\\]\\)\w+')
```

Challenges:
- Raw strings (`r""` in python)

**Comment by epage** [comment]
Moved over from #313 

> Hi, thank you for great tool! I'm trying to use this tool instead of misspell.
> 
> I saw one false positive in my project.
> 
> Let's say the following file is saved as `foo.go`.
> 
> ```go
> package main
> 
> import "fmt"
> 
> func main() {
> 	fmt.Println("welcome\nto this project")
> }
> ```
> 
> and run `typos` with the following command:
> 
> ```
> typos ./foo.go
> ```
> 
> Expected result is getting no error.
> 
> Actual result is:
> 
> ```
> error: `nto` should be `not`
>   --> foo.go:6:22
>   |
> 6 |  fmt.Println("welcome\nto this project")
>   |                       ^^^
>   |
> ```
> 
> This is because `typos` does not consider escaped character `\n`. Though I don't have good idea about how to handle it well since characters which can be escaped are depending on their syntax, one character just after `\` in string literals might work.

**Comment by epage** [comment]
@rhysd does go have a form of raw strings (no escaping performed)?  I'm wondering how misspell handles the challenges they provide.  For example, in Python its common to write regexes with raw strings so you don't have to double escape (e.g. `r"\b"` instead of `"\\b"` for word boundary)

**Comment by rhysd** [comment]
Yes, it has.

e.g.

```go
re := regexp.MustCompile(`\d+\.\d+\.\d+`)
```

ref: https://pkg.go.dev/regexp

**Comment by rhysd** [comment]
And I also guess the similar false positive would be around printf-like format (e.g. `"%dfoo"`).

**Comment by epage** [comment]
Since our primary concern is with having 100% confidence in the changes we make, a simple solution to this problem is to just not check words that start with `\`.  While it means we check less, it means we don't have to worry abut what is or isn't a raw string within each programming language.

Can't believe I hadn't thought of this before.

**Comment by groengpx** [comment]
The comparison docs still lists this as an open issue: https://github.com/crate-ci/typos/blob/84c8b30e065012c70187818aadba0e711ff5cafc/docs/comparison.md

Is that intended? From what I read here, it is fixed?

**Comment by epage** [comment]
Thanks!  I've fixed it
