### ISSUE TITLE
Some typos being missed

### ISSUE THREAD

**Issue by ciaranevans** [crate-ci/typos#312]
Hey Folks, 

I'd love to know what the sensitivity/harshness of the tool is.

For example, the following text generates **no** errors:

```markdown
spellingg is hard

This is a badd job of speling
```

But this does:

```markdown
Particularlly bad way of spelling
```

I'd love to use this tool as an Action against PRs to our documentation repositories, but it seems to be missing pretty obvious mistakes, even if I directly provide the full path to the file

Cheers!

**Comment by epage** [comment]
Sorry for the delay.

There will always be typos that we miss because we use a hard coded list of typos unlike traditional spell checkers that use a hard coded list of dictionary words.  This is so we reduce the chance of "correcting" a valid word, so that it *is* safe to run as an Action.

If you would like to contribute typos you find, you are welcome to do so!  I've updated [CONTRIBUTING.md](https://github.com/crate-ci/typos/blob/master/CONTRIBUTING.md#adding-typos) to describe how to do so, with correctness checks to reduce mistakes.  I've also done some scrounging for typos and am adding some more (https://github.com/crate-ci/typos/pull/315)

**Comment by Keavon** [comment]
That's very surprising to hear you use a blacklist not a whitelist. Might I suggest making that very clear in the project readme to dispell confusion? (You could also use that to link to the section in contributing.md.)

**Comment by epage** [comment]
> That's very surprising to hear you use a blacklist not a whitelist

Most [other tools in this space](https://github.com/crate-ci/typos/blob/master/docs/comparison.md) seem to use a blacklist as well

>  Might I suggest making that very clear in the project readme to dispell confusion?

The README links to [design.md](https://github.com/crate-ci/typos/blob/master/docs/design.md) which documents this.

I'm trying to think of what would be an appropriate other way to introduce this.  Maybe add a FAQ with the first item being about "why isn't this corrected?"

> (You could also use that to link to the section in contributing.md.)

[CONTRIBUTED.md](https://github.com/crate-ci/typos/blob/master/CONTRIBUTING.md) calls out the file format of `typo,correction[,correction...]`  though I have some thoughts on how to call this out more explicitly.

**Comment by epage** [comment]
Made some changes: https://github.com/crate-ci/typos/commit/ccbd1a69af7075c40f28a8ba7e3116e8447fe823

**Comment by ciaranevans** [comment]
Hey @epage thanks for the clarification and the **huge** addition of words in your change 🎉

**Comment by aminya** [comment]
I still think dictionary-based spell checking is useful. Could you add an optional feature to support that as well?

**Comment by epage** [comment]
`typos` entire design is centered around unattended corrections.  I would personally recommend splitting off another tool, built on `typos` core for that.

However, I would be willing to consider merging it in, depending on what the solution looks like and how it impacts the primary use case.  I will say that starting as an independent tool would make it easier to evaluate (a released tool that is collecting its own feedback, and not just a PR)

**Comment by aminya** [comment]
We can use the dictionaries that vscode-spell-checker is using. It supports many languages.
https://github.com/streetsidesoftware/vscode-spell-checker
