### ISSUE TITLE
Escaped characters in string literals are not considered

### ISSUE THREAD

**Issue by rhysd** [crate-ci/typos#313]
Hi, thank you for great tool! I'm trying to use this tool instead of misspell.

I saw one false positive in my project.

Let's say the following file is saved as `foo.go`.

```go
package main

import "fmt"

func main() {
	fmt.Println("welcome\nto this project")
}
```

and run `typos` with the following command:

```
typos ./foo.go
```

Expected result is getting no error.

Actual result is:

```
error: `nto` should be `not`
  --> foo.go:6:22
  |
6 |  fmt.Println("welcome\nto this project")
  |                       ^^^
  |
```

This is because `typos` does not consider escaped character `\n`. Though I don't have good idea about how to handle it well since characters which can be escaped are depending on their syntax, one character just after `\` in string literals might work.

**Comment by epage** [comment]
Moving the conversation for this over to #3.
