### ISSUE TITLE
RFE: better handling of ordinal numbers

### ISSUE THREAD

**Issue by scop** [crate-ci/typos#331]
Currently there are false positives like:

```shellsession
$ echo 2nd | typos - | head -n 1
error: `nd` should be `and`
```

One approach to these would be to treat everything where a sequence of numbers is followed by `th`, `nd`, or `rd` as ok.

But it would be nice to do better, e.g. in regex pseudospec, stopping at first match
```
([0-9]*11)st -> \1th
([0-9]*12)nd -> \1th
([0-9]*13)rd -> \1th
([0-9]*1)th -> \1st
([0-9]*2)th -> \1nd
([0-9]*3)th -> \1rd
([0-9]+)(nd|rd) -> \1th
([0-9]+)th -> <this is ok>
```

**Comment by epage** [comment]
My concern is that adding a dynamic dictionary would slow things down for a rare case.

Let's start by just ignoring ordinals in the parser

**Comment by scop** [comment]
That works for me, thanks for considering.

But just so I understand: ignoring ordinals would need to be done dynamically as well, right? Do you think the additional cost of doing the corrections while at it would be a concern?

**Comment by epage** [comment]
- The above is 8 parse attempts with 2 branches
- `[0-9]+(st|nd|rd|th)` is 1 attempt with 4 branches,

You are welcome to try both and benchmark it.  `cargo bench --bench checks` will give some idea of how it works (`Typos` group will include parse and correct) but to get the full idea, you'd want to run the end-to-end benchmarks 

So something like:
```bash
./benchsuite/uut/typos.sh download
./benchsuite/fixtures/ripgrep_built.sh download
./typos/benchsuite/fixtures/linux_clean.sh  download

./benchsuite/benchsuite.sh
# Backup the report, it has the date but not time in the file name

# Make a changes
./benchsuite/uut/typos.sh clean
./benchsuite/uut/typos.sh download

./benchsuite/benchsuite.sh
# Compare report
```

**Comment by scop** [comment]
I might do that one day.

I wasn't suggesting following my "regex pseudospec" to the letter -- it was a pseudo one just for illustration purposes. We could very well narrow it down with the `[0-9]+(st|nd|rd|th)` which we'd do anyway to ignore these, and only if that matches, do a few further comparisons within that branch to provide fixes if we find any.

In the grand scheme of things, assuming input not crafted specifically to provoke a bad case here, I still believe the overhead by the fixes would be negligible, if not almost unnoticeable in practice (possibly visible in benchmarks though) when done along those lines.
