### ISSUE TITLE
Skipping files during the ```typos``` workflow ?

### ISSUE THREAD

**Issue by Mohitkumar6122** [crate-ci/typos#359]
@epage, Can you provide me with a sample format that can skip files during ```typos``` workflow run ?
Something like this 
if I want to skip filename.json and Foldername during the ```typos``` workflow run?
```
with: 
        files:  ./filename.json
                ./FolderName/ 
        isolated : true
```

**Comment by epage** [comment]
This repo excludes some files via [`.ignore`]

liquid-rust doesn't ignore but it [sets other config](https://github.com/cobalt-org/liquid-rust/blob/master/typos.toml)

The `typos` command will pick these configurations up automatically unless you set `isolated`.

**Comment by Mohitkumar6122** [comment]
@epage, how can we add ```files.extend-exclude``` in the ```typos.yml``` ? 
I'm a bit confused regarding this, an example would be really appreciated!
PS : I am already using ```_typos.toml``` file but it is present in the root directory itself and I don't want to add too many files in the repository itself, so that's why I was wondering if I can add ```files.extend-exclude``` in the typos.yml file!

**Comment by epage** [comment]
> typos.yml

Do you mean `typos.toml`?  We don't support yaml.

If you do mean that, `typos.toml` and `_typos.toml` both work, see https://github.com/crate-ci/typos/blob/master/docs/reference.md

**Comment by Mohitkumar6122** [comment]
> > typos.yml
> 
> Do you mean `typos.toml`? We don't support yaml.
> 
> If you do mean that, `typos.toml` and `_typos.toml` both work, see https://github.com/crate-ci/typos/blob/master/docs/reference.md

No, I mean if I want to remove ```_typos.toml``` file and make those changes directly to the ```typos.yml``` file, how can we do it ?

Like is there any way in which I can use ```files.extend-exclude``` in the ```typos.yml``` file ?
PS :  I want to get rid of the extra config file to the ```typos```!

**Comment by epage** [comment]
Ok, didn't know you were referring to your workflow file.

At the moment, that is explicitly out of scope to control certain behavior outside of the config gile
- Thats a can of worms that can bloat the CLI / Action / Pre-commit
- We want consistent behavior between different people and with CI.
