### ISSUE TITLE
Pre-commit hook seems to ignore `_typos.toml`

### ISSUE THREAD

**Issue by insysion** [crate-ci/typos#360]
Typos gets false positives on our `yarn.lock` (as an aside, it's surprising to me that `.lock` files are check by default) so I added a `_typos.toml`:

```
[files]
extend-exclude = ["yarn.lock"]
```

This is respected if typos is invoked directly but not when invoked from pre-commit. Passing arguments to the hook does work and that is our current workaround.

**Comment by epage** [comment]
Thanks!

Been debugging this some and just realized that this is a duplicate of #347
