### ISSUE TITLE
Support for pyproject.toml

### ISSUE THREAD

**Issue by bdespond** [crate-ci/typos#361]
Is it possible to use the `pyproject.toml` directly instead of creating a specific `typos.toml` file?

**Comment by epage** [comment]
@dosisod something I overlooked in discussing this before was how this can affect looking for a config.

If someone has a `typos.toml` in the root of their repo and a `pyproject.toml` in a subdirectly without a `tool.typos` table, then they won't get their normal config.

We could also talk about whether we need to layer between config files with this change but I think we could save that discussion for another day

**Comment by jgillard** [comment]
I've seen this has been released, but it's not documented that `pyproject.toml` is now an option for configuring this tool. Was that an oversight or intentional? i.e. is it fully supported to now move config from the separate typos toml file into `pyproject.toml`?

**Comment by dosisod** [comment]
Thanks @jgillard , I forgot to document this. This feature should be good to go, you just need to relocate your settings to `[tool.typos.xyz]` instead of `[xyz]`.
