### ISSUE TITLE
Invalid corrections and false positives found when running `typos` in `elastio` repository

### ISSUE THREAD

**Issue by Veetaha** [crate-ci/typos#362]
Here are some false positives that we've found when running `typos` in our private Rust-based repository named `elastio`.

<table>
<tr>
	<td> Typo
	<td> Autocorrection
	<td> Expected
<tr>
	<td> block_devide
	<td> block_divide
	<td> block_device
<tr>
	<td> doen't
	<td> done't
	<td> don't/doesn't
<tr>
	<td> flate2
	<td> flat2
	<td> {none} (it's the name of a Rust crate)
<tr>
	<td> ser
	<td> set
	<td> {none} (it's the name a module `serde::ser`)
<tr>
	<td> impl_froms
	<td> impl_forms
	<td> {none} (it's the name of the macro that generates `From<T>` implementations)
</table>

And this seems to be it. This list is quite small. As for the size of the repo we have (quite a large one).

**Comment by Veetaha** [comment]
ping @epage

**Comment by epage** [comment]
Sorry, wasn't sure what was going on but the pause helped.  I realized I forgot to release some of the crates involved in this.  Doing so now.

**Comment by Veetaha** [comment]
> > I agree this is arguable and probably just fixable with better naming from the user's side, it was just not pleasant to see valid > > code corrected by typos which makes running it as a pre-commit hook that writes changes not possible, but it could run at > > least in fully fallible manner requiring the developer to run typos -w manually if they want to fix typos

> Please create an issue for this so we can track it separate from the rest of this conversation

I don't think this merits bikeshedding. As I said, this is arguable, so we just changed to a better naming.

Anyway, thank you very much for this tool, and for addressing our report. I very much appreciate this!
