### ISSUE TITLE
Binary published to `crates.io` is not the same binary published to github releases

### ISSUE THREAD

**Issue by Veetaha** [crate-ci/typos#375]
We have the same problem as in https://github.com/crate-ci/typos/issues/362#issuecomment-959728926.

If you install the binary via

```
cargo install typos-cli
```

the installed binary won't use the same typos database as the binary downloaded form github releases.
The version of `typos` in question is `1.3.0`.

**Comment by epage** [comment]
Fixed

Going to also update my release process to avoid running into this again
