### ISSUE TITLE
Capalization makes typos think word is misspelled

### ISSUE THREAD

**Issue by aaronraimist** [crate-ci/typos#399]
Running typos on

> tail the logs for ERRORs and report them

results in

```
error: `ERRO` should be `ERROR`
  --> ./test.txt:1:18
  |
1 | tail the logs for ERRORs and report them
  |                   ^^^^
  |
 ```

even though it is spelled correctly.

Additionally, adding this false positive to `default.extend-words` is less than ideal because it doesn't accept `ERRORs = "ERRORs"` or `ERROR = "ERROR"`. Only `ERRO = "ERRO"` will make typos not fail.

**Comment by epage** [comment]
We spell check in two passes, first the identifier and then with standard word splits (snake_case, kebab-case, CamelCase).

This can be added to the `extend-identifiers` to prevent it from coming up.  Another workaround is to re-word to 
```
tail the logs for `ERROR`s and report them
```

Beyond that, the challenge is how to recognize this case vs potential camel cases.

**Comment by epage** [comment]
While this is common enough, I think I'm going to say this is out of scope as there isn't any way for us to automatically differentiate this from any other spelling.
