### ISSUE TITLE
unknown field `extend-globs` for key

### ISSUE THREAD

**Issue by bgr** [crate-ci/typos#404]
I copied the following part from the readme to my `_typos.toml` file:

    [type.po]
    extend-globs = ["*.po"]
    check-file = false

and now running the program gives the following error:

    unknown field `extend-globs` for key `type.po` at line 1 column 1

Note that the line number says 181, but it's at the beginning of my `_typos.toml` file.

typos-cli 1.3.5 on Windows

**Comment by epage** [comment]
This is a typo in the docs.  I'm preparing a PR that fixes it.  The field should be `extend-glob`.

Points to you for getting issue 404 for an unknown field.

**Comment by epage** [comment]
Released in v1.3.6
