### ISSUE TITLE
Bad line number in error message

### ISSUE THREAD

**Issue by bgr** [crate-ci/typos#405]
Using the following `_typos.toml`:
```
[type.po]
extend-globs = ["*.po"]
check-file = false

[type.tga]
extend-globs = ["*.tga"]
check-file = false

[type.psd]
extend-globs = ["*.psd"]
check-file = false
```
results in the following error message:

    unknown field `extend-globs` for key `type.po` at line 9 column 1

Basically the error message refers to first line, but line number depends on total number of lines.

**Comment by epage** [comment]
Switching toml parsers means we are losing this until ordian/toml_edit#303 is implemented.
