### ISSUE TITLE
How to extend words for custom file type?

### ISSUE THREAD

**Issue by bgr** [crate-ci/typos#407]
Based on what I saw in `typos --dump-config -` I tried to introduce my own file type and extend words for it, like this:
```
[type.shaders]
extend-glob = [
  '*.shader',
  '*.cginc',
]

[type.shaders.extend-words]
inout = "inout"
```
but this results in the following error:
```
unknown field `extend-words` for key `type.shaders` at line 7 column 1
```
Shouldn't this work?

**Comment by epage** [comment]
Released in v1.3.6
