### ISSUE TITLE
Missed typo that is in the list

### ISSUE THREAD

**Issue by afranke** [crate-ci/typos#411]
In https://github.com/matrix-org/matrix-doc/pull/3658#discussion_r792092382 the misspelt word ("defintions" instead of "definitions") was not caught, but it *is* already in `words.csv`.

CC @aaronraimist who added the CI workflow.

**Comment by epage** [comment]
Thanks for reporting this!

It looks like our tokenizer has a bug where its incorrectly ending at templates.  In this case, its ending at:
```
Some API endpoints may allow or require the use of `POST` requests
without a transaction ID. Where this is optional, the use of a `PUT`
request is strongly recommended.

{{% http-api spec="client-server" api="versions" %}}
```
(I used the `--identifiers` flag to discover this)

**Comment by epage** [comment]
v1.3.8 is released with the fix
