### ISSUE TITLE
Typo detected in URL

### ISSUE THREAD

**Issue by mynamewastaken** [crate-ci/typos#433]
```
error: `ba` should be `by`, `be`
  --> content/team/index.md:32:400
   |
32 |         <a href="https://xxx.service-now.com/nav_to.do?uri=%2F$oc.do%3Fsysparm_include_view%3Ddaily,weekly,monthly%26sysparm_timezone%3DUS%2FCentral%26sysparm_timeline_enabled%3Dfalse%26sysparm_current_view%3Dmonthly%26sysparm_group_id%3Dxxx%26sysparm_rotas%3Dxxx%26sysparm_rosters%3Dxxx%26sysparm_show_gaps%3Dtrue%26sysparm_show_conflicts%3Dtrue%26sysparm_start_date%3D2022-02-04">On-Call Calendar</a>
```

I've stripped out part of the url, but it's flagging a 35 char string of hex as a typo. My workaround for now was to ignore the `index.md` files as they are basically static content.

**Comment by epage** [comment]
I've copied that line into a file and ran typos v1.4.0 against it and ma not seeing any problems.

What version of typos are you using?  If you isolate it into a single file and run typos against it, do you see the message?

**Comment by mynamewastaken** [comment]
Hi,

Just updated to 1.4.0 (was on 1.3.3) and I still see the same error. I noticed the error goes away if I strip out the comma separating the hex strings.
e.g. `https://xxx.com/.*[a-z0-9]{35}/` does not trigger the error, whereas `https://xxx.com/.*[a-z0-9]{35},[a-z0-9]{35}/` does seem to. Hopefully that makes sense

**Comment by epage** [comment]
Thanks for helping to narrow it down!  I've got a PR up to get us closer to RFC 3986

**Comment by mynamewastaken** [comment]
@epage Thanks for the quick update! Can confirm this fixed the issue.
