### ISSUE TITLE
ignore go.sum by default

### ISSUE THREAD

**Issue by georgettica** [crate-ci/typos#458]
in the same way https://github.com/sharkdp/fd has a --no-ignore or --hidden flags, we should automatically not search `go.sum` for typos (as it's generated I think)

**Comment by epage** [comment]
This is effectively a lock file, yes?

If we add it to our ["lock" file type](https://github.com/crate-ci/typos/blob/master/src/default_types.rs#L149), we'll then [stop checking the file](https://github.com/crate-ci/typos/blob/master/src/config.rs#L178)

**Comment by epage** [comment]
Mind taking a look at https://github.com/crate-ci/typos/pull/459 to see if the description and actions taken line up with a go users expectations?

**Comment by georgettica** [comment]
This looks great, thank you!

**Comment by georgettica** [comment]
Testing soon

**Comment by georgettica** [comment]
it works!
glad this was merged :)

**Comment by georgettica** [comment]
@epage found this works great but I now have an issue in go.mod
this shows the imports that can be done, and sometimes we use a hash to describe a version..

this is less obvious to fix as we need to ignore the version from scanning
```
module example.com

go 1.18

require (
        foo.com/pkg somebadhash
)
```

we need to ignore the `somebadhash` in go.mod

**Comment by epage** [comment]
Unless we do something special go.mod, this falls under https://github.com/crate-ci/typos/issues/415 which we've not had a good solution for yet.
