### ISSUE TITLE
[question] Ignore hex color value

### ISSUE THREAD

**Issue by jsonz1993** [crate-ci/typos#462]
Hello, when I use it, I found that there are some scenes that do not need to be corrected. For example, when expressing colors in hexadecimal in a stylesheet file, e.g. `color: #ba431b`

error: `ba` should be `by`, `be`
  --> ./index.less:3:9
  |
  |   color:#ba431b

How should I handle this situation better, ignoring the whole *.less ? Or use `default.extend-words`

**Comment by epage** [comment]
v1.7.0 is released with support for detecting and ignoring CSS colors.
