### ISSUE TITLE
`--exit-zero`

### ISSUE THREAD

**Issue by eggplants** [crate-ci/typos#472]
I want `--exit-zero` option. Especially in CI workflow, it makes easier to ignore errors even if any typos are found.

e.g) 
`flake8 --exit-zero`
https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-exit-zero

**Comment by epage** [comment]
I'd be interested in knowing more about the use case.  Is there a reason you don't want to ignore bad exit codes, like wanting to make sure there aren't config errors?

**Comment by eggplants** [comment]
I often use this tool in pre-commit. But some errors are bothersome and wrong. So I want to make typos check-only and ignorable.

**Comment by epage** [comment]
So you want it to be advisory only but are running in a context where the exit code can be ignored (at least not seeing a field for it unlike CI config).  With a new flag, you can use the `args` field in pre-commit to get the behavior you want.

Not the greatest fan of flake8's name for this but not finding many other examples of tools that provide this.  Know of any others?

I think it'd be good to still error in cases besides typos but that isn't clear with `--exit-zero`.  In some tools internal to a company, I just called it `--failure-code NUM` for being a linter failure vs other types of failures.

**Comment by arminrosu** [comment]
Would this work instead?

`typos --format brief . || echo "Typos failed, I'll let you off with a warning this time."`

**Comment by eggplants** [comment]
I would like to use in pre-commit like this:

```yaml
  - repo: https://github.com/crate-ci/typos
    rev: v1.10.2
    hooks:
      - id: typos
        args: [--exit-zero]
```

**Comment by arminrosu** [comment]
You mean you want to continue your Github Actions Workflow (which you set up to check your commits) even if the typos step fails?

Does https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error not work?
