### ISSUE TITLE
Binary files produce invalid GitHub Actions annotations

### ISSUE THREAD

**Issue by jplatte** [crate-ci/typos#504]
![Screenshot_2022-06-22_175104](https://user-images.githubusercontent.com/951129/175081251-1b3e7d14-e06f-4373-a4e2-6fb088ccb645.png)

(`Style` is the name of the CI job)

comment by @epage from #501:

> Oh, I bet this is for the json message we output for binary files. We don't filter those out, so we are creating these annotations for them.

**Comment by epage** [comment]
1.10.2 is now released with the fix
