### ISSUE TITLE
analysis report

### ISSUE THREAD

**Issue by kasperk81** [crate-ci/typos#513]
a "report" feature would be great for this tool. something which can highlight important stuff like:

* total number of typos
* top N typos and their count: `1. "tyop" -> "typo" (42)\n2. "tpyo" -> "typo" (41)` and so on..
* top N possible false positives

suggestion:
```
$ typos --analyze
```

**Comment by epage** [comment]
I'm a bit hesitant with how varied the recommended analysis is.    This makes it feel open ended when I'd prefer a more closed-ended / well defined scope.  For one off analysis, users can use the json output.

**Comment by kasperk81** [comment]
i don't have strong opinions on wholesome analysis. if more granular options are preferred, we can consider one for:

> top N typos and their count

`$ typos --top <N>`

this will help triaging / prioritizing fixes in large repositories (where the user typically don't want all-or-none kind of change, but plan fixes / exclusions based on number of occurrences).
