### ISSUE TITLE
Hex/base64 detection is not aggressive enough

### ISSUE THREAD

**Issue by ammario** [crate-ci/typos#526]
I understand that `typos` detects long hex/base64 strings, but many of my strings are quite short and are detected as typos. It's impractical for me to add a bunch of strings like `3afe` and `ba348c` to my typos configuration.

`typos` has to strike a balance that may not work for anyone, so I'm asking for either more tunability or regex based extension. I prefer regex based extension since I can then match on more specific qualities like `---- BEGIN SSH2 PUBLIC KEY ----`.

**Comment by epage** [comment]
Going to close this as a duplicate
- In specifically looking for excludes, see https://github.com/crate-ci/typos/issues/316
- For heuristic solutions, see https://github.com/crate-ci/typos/issues/484

The more general issue is https://github.com/crate-ci/typos/issues/415
