### ISSUE TITLE
Some misspelled words are not reported

### ISSUE THREAD

**Issue by am11** [crate-ci/typos#528]
For example:
> It currnetly only simplies expressions without parentheesis.

There are three typos in this sentence: `currnetly`, `simplies` and `parentheesis`.

However, `typos` only reports one error:

```sh
$ echo "It currnetly only simplies expressions without parentheesis." > foo.txt

$ typos foo.txt
error: `simplies` should be `implies`, `simplifies`
  --> foo.txt:1:19
  |
1 | It currnetly only simplies expressions without parentheesis.
  |                   ^^^^^^^^
  |
```

**Comment by epage** [comment]
In case you aren't aware, check out "Why was ... not corrected?" in our [FAQ](https://github.com/crate-ci/typos#why-was--not-corrected)

We can always add more corrections though.

**Comment by am11** [comment]
Thank you for the pointer (I was not aware). It makes sense and now I understand that the design choices and tradeoffs justify this behavior.

By the way, in my limited research, I have found this a great tool with sanest defaults in this category, and it works well with git repositories. :slightly_smiling_face:

**Comment by epage** [comment]
Looking back on this, I feel like everything is resolved.  If there is more input, we can re-open or a new issue can be created.
