### ISSUE TITLE
`thead` is a key word for HTML

### ISSUE THREAD

**Issue by uyarn** [crate-ci/typos#532]
Hi, @epage, `thead` is a key word for HTML (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead)
and crate-cli/typos@v1.11.0 correct it as `thread`.
we got error: `thead` should be `thread` with crate-cli/typos@v1.11.0, refer to this CI https://github.com/Tencent/tdesign-vue/runs/7824112702?check_suite_focus=true
could you please release a new version to fix it, thank you :)

**Comment by epage** [comment]
Thanks for reporting this!

I wish I knew of a list of keywords for all major languages, HTML tags, common functions from different languages, etc so we could have a check in CI to prevent adding corrections for them

**Comment by uyarn** [comment]
> Thanks for reporting this!
> 
> I wish I knew of a list of keywords for all major languages, HTML tags, common functions from different languages, etc so we could have a check in CI to prevent adding corrections for them

exactly, probably we need a list of keywords to check whether the typo need to be corrected or not
