### ISSUE TITLE
Consider fully removing 'thead' suggestion again

### ISSUE THREAD

**Issue by jplatte** [crate-ci/typos#560]
After posting #559 to get rid of the `thead` problem in one codebase, I checked again with the other one that was affected and found that it used `thead` in a Rust source file, as a string literal in some code sanitizing HTML:

https://github.com/ruma/ruma/blob/9e3ac10c6285b0e77b409d094fcecef5cbe6edc1/crates/ruma-common/src/events/room/message/sanitize/html_sanitizer.rs#L235-L241

I think one will be able to find examples of similar things in pretty much all programming languages. To me, a major selling point for typos is its aspiration of zero false positives, so I think it may be better to remove this suggestion entirely.

**Comment by epage** [comment]
There is always the risk of references from other languages (or cultures) causing problems like this and I've previously taken the approach of punting and saying 'that is what user configuration is for".

However, HTML is so ubiquitous, and thead particularly, that I should probably relent.
