### ISSUE TITLE
False positive for NDArray

### ISSUE THREAD

**Issue by tianyicui-tsy** [crate-ci/typos#565]
In my Python code, I use

```
from numpy.typing import NDArray
```

And `typos` currently would correct `NDArray` to `ANDArray`.

I fixed this by adding this identifier to my local `_typos.toml` but it'll be great if it can be fixed for others too.

**Comment by epage** [comment]
v1.12.4 is now released

**Comment by eismont21** [comment]
It is still failing in Jupyter notebooks
