### ISSUE TITLE
pre-commit default behavior

### ISSUE THREAD

**Issue by wyfo** [crate-ci/typos#570]
This is not an issue but a question related to pre-commit hook.

Typos are not easily noticeable, so when some of them are fixed by the pre-commithook, it's difficult to spot what has been changed.
I run at this issue today, in a file where there was some Azure commands : `az aks ...`. Commands were "fixed" to `az ask ...`.

My point is that the hook default behavior can be "dangerous", as it may break things quite silently (contrary to a formatting hook for example, which normally cannot break anything, so it can be applied safely).

I know this is possible to override the default behavior with `args: []`, but IMO, the default behavior should be changed to make it safer.
What do you think?

**Comment by epage** [comment]
The overall goal of typos is to be safe to run unattended.  If there are corrections that shouldn't happen, those are generally considered bugs (unless in a code-base specific context)
