### ISSUE TITLE
Release Action's confusion over tagging can cause some Releases to not be created

### ISSUE THREAD

**Issue by kylecarbs** [crate-ci/typos#590]
I'm not sure why, but it seems like a tag was published for v1.12.9 but the binaries weren't built and uploaded. This is actively breaking our CI, so help would be appreciated!

**Comment by kylecarbs** [comment]
It doesn't seem like I can pin a version either, so I'm just stuck in a broken state.

**Comment by JohnDoneth** [comment]
We're having the same issue. It appears we can pick a version by supplying it as the `VERSION` environment variable. I will look into doing that so we don't get any more CI breaks.

**Comment by epage** [comment]
There is always a delay between the tag being created and the actions adding the binaries to it.  The binaries should be uploaded now.

When you specify the action, instead of `master`
```yaml
    - name: Spell Check Repo
      uses: crate-ci/typos@master
```
You should be able to select a specific version based on the tag
```yaml
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.12.8
```
If its not using the selected version then thats a bug

**Comment by jplatte** [comment]
> The binaries should be uploaded now.

Doesn't seem like it, https://github.com/crate-ci/typos/releases/download/v1.12.9/typos-v1.12.9-x86_64-unknown-linux-musl.tar.gz still returns 404 ([CI log](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/3197607729/jobs/5222325392)).

**Comment by epage** [comment]
Oh, got mixed up on which versions I was looking at.  I've deleted that tag for now.  Can't see why it didn't trigger the post-release action to make the binaries

**Comment by epage** [comment]
Haven't seen this in a while; assuming its fixed.
