### ISSUE TITLE
Chokes on an UTF-16LE file

### ISSUE THREAD

**Issue by ILoveGoulash** [crate-ci/typos#641]
Hello, said file has a correct (i.e. `ff fe` in hexdump) BOM, too; emacs has no problem with it either. Here's a simple reproducer:
[test.zip](https://github.com/crate-ci/typos/files/10303907/test.zip)
```
$ typos --version
typos-cli 1.13.6
$ unzip test.zip
$ typos test
[error] : incomplete sequence
```

This is on Fedora 37 with an UTF-8 locale.

**Comment by epage** [comment]
We correctly detect the file is UTF-16LE but the decoder fails.  We have the decoder set to strict mode to reduce risk of us reading in a file and corrupting it through the decode/encode process.

**Comment by ILoveGoulash** [comment]
I see, but I wonder if it's a bug in the decoder or truly a problem with the example (not well versed in UTF-16).

**Comment by epage** [comment]
Thats what I get for assuming we had UTF-16 tests and missing critical parts of an API.

It should be fixed now.

**Comment by fdncred** [comment]
> It should be fixed now.

Indeed it is. Thanks for the quick turnaround.

**Comment by epage** [comment]
@ILoveGoulash can you confirm this is still an issue with our new UTF-16 decoder?

**Comment by epage** [comment]
Without any word, I'm assuming it is resolved.  If this is a still a problem, we can always re-open
