### ISSUE TITLE
Shell command short parameters typo false positive

### ISSUE THREAD

**Issue by pdostal** [crate-ci/typos#643]
In bash scripts, `typos` sometimes tries to do the following:
```diff
- wget -r -l1 -np -nd '$base_url' -A $iso
+ wget -r -l1 -np -and '$base_url' -A $iso
```

Would that be possible to ignore that?

**Comment by epage** [comment]
atm there isn't much for this.

I can't think of a heuristic for us to help in these cases like in #484.

In #316 we talk of ways of telling typos to not do checks.

**Comment by epage** [comment]
FYI #695 provides a new workaround for false positives
