### ISSUE TITLE
Upload to PyPI?

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/typos#649]
We've had typos running in https://github.com/PRQL/prql recently and it's been great! 

I see there's a `setup.py` here, and we can install with `pip`. Would it be possible to upload this to PyPI so we install with `pip install typos`? It'd be great to also use it in environments which don't have access to GitHub.

I have very little context for whether this is possible, so feel free to close without much explanation...

**Comment by epage** [comment]
The `setup.py` is a shim to more easily integrate with pre-commit.  I would feel weird uploading something to PYPI that has absolutely no python code to it.

**Comment by max-sixty** [comment]
> uploading something to PYPI that has absolutely no python code to it.

I read a blog post that I'd read discussing exactly this, but I can't find it unfortunately. I get the impulse; though pip is a nice way to distribute apps.

I'll close — thanks for the consideration though

**Comment by max-sixty** [comment]
FYI I found the blogpost I was thinking of! 

https://simonwillison.net/2022/May/23/bundling-binary-tools-in-python-wheels/

**Comment by neiljp** [comment]
I was looking for this too, after being pointed at `typos`, and also found the `setup.py`.

However, the new python linting tool `ruff` is written in rust, and uses `maturin` to simplify the wrapping - could that simplify install with pre-commit too? `typos` is arguably a linting tool too - with support for snake case - and `maturin` itself is uploaded to PyPI.

I couldn't find a specific policy for non-python tools on PyPI.

**Comment by epage** [comment]
`ruff` is a bit different as its sole target audience is Python developers and its meant to be a drop-in replacement for flake8.  It should look like any other python tool.

With that said, I am playing a bit with maturin (#675).  Not a fan of how many CI jobs get created.  I'm tempted to drop esoteric platforms (e.g. ppc) and make it a best-effort (only runs on tags, not for PRs).  Would that be too negative of an experience to be worth it?

**Comment by max-sixty** [comment]
That would be great! We only run the maturin job on merges rather than each PR.

I'd also love a release to PyPI, but ofc respect your decision if you're not so keen.

**Comment by epage** [comment]
Latest release is on PyPI.  Someone want to give it a try?

**Comment by neiljp** [comment]
This works as well as the previous version I tried from `setup.py` 👍 

There's also the upside of indicating the package name, from the point of view of tracking installation 🎉 

I did notice that (just like with ruff, it seems) uninstalling the package and trying to run the command gives a bash error, but that's minor to address later (or in maturin?)

**Comment by epage** [comment]
So now to get pre-commit to use this new package and drop the setup.py...

**Comment by neiljp** [comment]
Will releases now all get pushed to PyPI?

**Comment by epage** [comment]
Yes, one of the reasons I was willing to go forward with this is it is automated.  I maitnain my existing release process and packages will automatically get uploaded to PyPI

**Comment by sadikkuzu** [comment]
I get `CalledProcessError` just after [github.com/crate-ci/typos: v1.13.18 → v1.13.20](https://github.com/crate-ci/typos/compare/v1.13.18...v1.13.20)
https://results.pre-commit.ci/run/github/352429220/1678725815.r_EVoR0WTOmyecm6BOu7ng

Same for v1.13.19 🚫 

However, v1.13.18 is ok ✅ 
https://results.pre-commit.ci/run/github/352429220/1678742341.tuT2sVnbTTWBaozYfTj6KA

**Comment by epage** [comment]
@sadikkuzu can you try 1.13.21?  That was the release where pre-commit became a wrapper in hopes that pre-commit will install pre-built wheels, rather than building from scratch

Also, if they lack `cargo`, I wonder how they handle the growing use of Rust in Python (ruff, cryptography, etc).  Always hoping wheels exist?

**Comment by sadikkuzu** [comment]
Well, `1.13.22` seems ok. Thanks @epage
