### ISSUE TITLE
Exclude identifier via regular expression

### ISSUE THREAD

**Issue by vsoch** [crate-ci/typos#651]
We have job identifiers that look like this:

```
jobid: ƒABaWMZ7UmD
```
They are all over our documentation, with the ending of the identifier varying. I haven't been able to figure out how to ask typos to ignore a regular expression for any string that starts with f*. It always errors:

```console
error: `Ba` should be `By`, `Be`
  --> faqs.rst:385:12
    |
385 |   jobid: ƒABaWMZ7UmD
```
Could this be possible to support?

**Comment by epage** [comment]
I feel like this is an orthogonal route to #316.  The main thing that needs to be figured out is the config file design.

**Comment by vsoch** [comment]
Maybe similar? But for the case here, I wouldn't want to just ignore an entire line - e.g., we use these identifiers in sentences to talk about them, and we'd want those spell checked.

**Comment by vsoch** [comment]
I'm guessing it's not so simple as just doing a regex to replace the "skips" with empty space and checking the rest?

**Comment by epage** [comment]
So the original title talks about excluding identifiers, ie what you get when you run `typos --identifiers`.  I see this being similar to how you can extend `typos` to spell check your own identifiers .... or signify your identifier should never be corrected.  See [`extend-identifiers`](https://github.com/crate-ci/typos/blob/master/docs/reference.md).

We could have a similar field in the config, like `extend-ignore-identifiers-re` that let you build up a collection of regexes that when matched against an identifier, get ignored.  I was more commenting on what the config field name should be and the precise semantics (e.g. exclusively be regex or allow it to be configured also as globs, etc)

**Comment by vsoch** [comment]
Ah gotcha! 

> We could have a similar field in the config, like extend-ignore-identifiers-re that let you build up a collection of regexes that when matched against an identifier, get ignored. I was more commenting on what the config field name should be and the precise semantics (e.g. exclusively be regex or allow it to be configured also as globs, etc)

I would err on the side of being explicit, if someone sees "re" that is very different than "glob" so perhaps start with `extend-ignore-re` and if there is noise for more of a glob functionality, that could be added separately as `extend-ignore-glob`. I do think both could eventually be wanted, because some people like writing regular expressions and others want to add a `<glob>*` and know that will work. As long as there are good examples in the README it should be clear how they differ.

**Comment by epage** [comment]
Normally I prefer glob so long as it works but I think in this case, the cases are likely too complex for glob.
