### ISSUE TITLE
Informative: `typos` is now added to conda-forge

### ISSUE THREAD

**Issue by DamianBarabonkovQC** [crate-ci/typos#666]
I want to let you know that I added `typos` to conda-forge. It has Windows, Linux, Mac OSX (including arm64) support. This may be useful to `conda install typos` in a system when `cargo` or `brew` are unavailable.

Relevant feedstock: https://github.com/conda-forge/typos-feedstock

There was a use-case at work where I needed to access `typos` through conda-forge, since that was the only source the firewall would allow packages to come from. That's an aside. But it may be useful to others who simply do not want to use `cargo`.

This is not an issue, rather simply informational.

**Comment by epage** [comment]
Thanks!  Do you want to do a PR for install instructions or should I?

Is this self-updating or does someone have to maintain it?

**Comment by DamianBarabonkovQC** [comment]
I am the maintainer. I'll create a PR for the README.
