### ISSUE TITLE
【Bug】can not find typos-v1.13.15-x86_64-unknown-linux-musl.tar.gz

### ISSUE THREAD

**Issue by PengYYYYY** [crate-ci/typos#673]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/35833812/222318602-771c4ba8-15d6-4ae3-a3d6-2f17110393f6.png">

maybe v1.13.15 have some problem?

**Comment by epage** [comment]
I had hoped a recent change would have made the release pipeline work but apparently not. v1.13.16 was released in a way that should generate artifacts.

**Comment by PengYYYYY** [comment]
thanks
