### ISSUE TITLE
Non-critical corrections - March 2023 Edition

### ISSUE THREAD

**Issue by jplatte** [crate-ci/typos#677]
Please list any corrections you noticed `typos` doesn't fix and we'll roll these up into a single PR, making it lighterweight for adding new corrections.

**Comment by jplatte** [comment]
- `empheral` -> `ephemeral` (#676)
- `referenecs` -> `references`

**Comment by epage** [comment]
**Meta**: We can try for a per-month issue for this for now.  My original thought had been to use a Discussion with the current "correct answer" being the current month.  This would provide a stable link for places like the README to use.  The downside is its too easy for people to reply in the wrong thread / create a new thread and Github doesn't have the thread-editing tools of Zulip afaik

**Comment by epage** [comment]
- `configurating` -> `configuring`
- `configurating` -> `technical`
- `signficiantly` -> `significantly`
- `substitues` -> `substitutes`

Source: rust-lang/cargo#11794 (found after rust-lang/cargo11561)

**Comment by jplatte** [comment]
**Meta:** I think the nice things about an issue are

- you can pin it (though maybe this is a thing for discussions too)
- people are more used to issues and go there first

But I think that's it really, mostly I did it this way because that's what came to mind for me. I'll be happy to suggest new corrections elsewhere if you decide to try sth. else at any point.

**Comment by adamchainz** [comment]
`encryptation` -> `encryption`

**Comment by cmdcolin** [comment]
deature->feature
