### ISSUE TITLE
Github Action can sometimes be slow do to building of the image

### ISSUE THREAD

**Issue by WaterLemons2k** [crate-ci/typos#678]
Currently using Docker to run GitHub Action, its required to building the image every time so it's too slow. Run it using Node.js to make sure it's faster.
We can use https://github.com/ad-m/github-push-action/blob/fe38f0a751bf9149f0270cc1fe20bf9156854365/start.js to execute a Shell script.

Action using node: https://github.com/WaterLemons2k/typos/actions/runs/4390226555

I would like to open a PR for this issue if possible.

**I don't know much about Rust and Node.js, so please excuse my mistakes.**

**Comment by WaterLemons2k** [comment]
We use docker to run this action as it is needed to run the shell script and we can use node to run it so that we don't have to build the image.

If you don't want using node, there's another solution called [composite](https://docs.github.com/actions/creating-actions/creating-a-composite-action), but we need more code than node.

**Comment by WaterLemons2k** [comment]
Sorry @epage, but which action do you want to use? node or composite?

**Comment by epage** [comment]
Like I said, I'd prefer no JS, so I would lean towards composite.

**Comment by WaterLemons2k** [comment]
Opened #687.
