### ISSUE TITLE
commitish -> committish false-positive?

### ISSUE THREAD

**Issue by tekumara** [crate-ci/typos#690]
typos corrects `commitish -> committish` ...

But both are valid according to the [git glossary](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefcommit-ishacommit-ishalsocommittish).

I've hit this because I'm using the [github api](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28) which has `target_commitish`.

Is this something that could be fixed? or do you recommend I just add this to my _\_typos.toml_ ?

**Comment by epage** [comment]
Technically, the glossary lists one of those as hyphenated and the other not but I don't think its worth being a stickler about.
