### ISSUE TITLE
How to deal with false positives caused by hash digests

### ISSUE THREAD

**Issue by fox-222** [crate-ci/typos#699]
When there is a digest in the `.md` file, there may be false positives, as seen [here](https://github.com/MystenLabs/sui/pull/9879/files).

After reading the documentation, adding all digests to `typos.yml` would be a bit strange, and ignoring this file is not an option (because I see that sui uses typos to check for spelling errors in the document).

So what is the best practice here?

**Comment by epage** [comment]
Related issues
- #438
- #415
- #413
- #401

In the latest release, we added support for `extend-ignore-re` which allows you to define custom ignorables like for your digest. 

I'm inclined to close this in favor of `extend-ignore-re` and the above issues (iirc one of them includes a more general heuristic for ignoring "garbage")
