### ISSUE TITLE
Typos reports typos in _typos.toml

### ISSUE THREAD

**Issue by emilk** [crate-ci/typos#711]
Adding your own `extend-words` is quite problematic:

```
❯ cat _typos.toml 
[default.extend-words]
grey = "gray"

❯ typos
error: `grey` should be `gray`
  --> ./_typos.toml:2:1
  |
2 | grey = "gray"
  | ^^^^
```

I would suggest typos ignore its own configuration file when checking for typos

**Comment by MAHDTech** [comment]
You can ignore the config files if you create a `.ignore` file in the root of your repo, you can add this.

```
# Ignore any typos config files
typos.toml
_typos.toml
.typos.toml
```

Then add the flag `--ignore-dot` when you run typos.

**Comment by emilk** [comment]
Yeah, I can also add it to `_typos.toml` itself:

```toml 
[default.extend-words]
grey = "gray"

[files]
extend-exclude = ["_typos.toml"]
```

it just feels a bit silly that the default behavior is that `typos` trips on its own config file

**Comment by epage** [comment]
There are a couple of ways for us to fix this
- Automatically put it in `extend-exclude`
  - This would allow someone to explicitly do spell checking of the file if they want (`typos _typos.toml`)
- Add a new filetype and exclude chekcing the file by default
- Hard code this directly in the source

Any thoughts on what approach to take?

**Comment by emilk** [comment]
For me it makes sense to hard-code `typos` to ignore its own config files since the main purpose of the config files is to contain typos and their corrections
