### ISSUE TITLE
RFE: ignore build system input `.in` extension when determining the type

### ISSUE THREAD

**Issue by scop** [crate-ci/typos#727]
Would be good to strip known template/backup filename extensions before attempting a match against a filename/extension glob.

Here's an implementation of that I did some time ago for `bat`: https://github.com/sharkdp/bat/pull/1687

**Comment by epage** [comment]
Template files are a weird case because they contain multiple languages.  Which language should we check?

For backup files, I assume we would instead want to ignore all of them.

**Comment by scop** [comment]
Right, ignoring backups would make sense for typos.

Regarding templates, the case I'm mostly interested in is the `.in` generic build system input one; for that I think the right thing to do is to strip the suffix and decide based on what's left in the name after that. I don't remember coming across one that would actually have multiple languages in it, but just some placeholders to be replaced.

For this specific case, using appropriate type specific extend-globs like
```toml
[type.sh]
extend-glob = ["*.sh.in"]
```
...does seem to serve as a workaround for the time being.

**Comment by epage** [comment]
> I don't remember coming across one that would actually have multiple languages in it, but just some placeholders to be replaced.

I was referring to when you have a template language mixed in with the generated output.

You could say php/html is an example of this.  See also liquid, tera, ninja, handlebars, etc.

**Comment by epage** [comment]
Another aspect of backups is that hopefully they are gitignored (in the per-user ignore file) which typos will then ignore by defalt.

**Comment by scop** [comment]
Right, agreed on both, and the PHP example is an interesting one.

Anyway as far as I'm concerned, this RFE reduces to just stripping the literal trailling `.in` suffix (recursively, as at least `*.in.in` are a pattern in use in some cases too) before attempting filename based type finding.

**Comment by epage** [comment]
I'd be fine with just stripping `.in`
