### ISSUE TITLE
".github/" is ignored by default

### ISSUE THREAD

**Issue by kachick** [crate-ci/typos#779]
Please let me know if there is another way. 🙏 

Background
---

The `.github/` path will contain many YAML files for configuration. Especially GitHub Actions workflows.
It is basically managed by git, however typos exclude files under the path from `files.ignore-hidden = true` by default.

```console
> typos --version
typos-cli 1.16.0
> typos -vvv 2>&1 | grep -F .github
[debug] ignoring ./.github: Ignore(IgnoreMatch(Hidden))
> typos --dump-config - | grep ignore-hidden
ignore-hidden = true
```

As I understand it, if I want to enable typos for the files, I should do one of the following.

- Add arguments to call typos as `typos . .github`
- Put `_typos.toml` which will disable all other dots again
  ```toml
  [files]
  ignore-hidden = false
  extend-exclude = [".git", '.direnv', '.bundle']
  ```

I want to prefer no arguments call of typos, so putting config is okay.
But it always requires editing the `extend-exclude` option for each GitHub repository.

Feature Requests
--

One of the following will help me a lot.

- Exclude `.github/` from `files.ignore-hidden` targets
- `files.extend-exclude` will accept `!` prefix as `.gitignore`
- New option `files.extend-include`

**Comment by epage** [comment]
Ignore-hidden won't be getting special cases as that is dependent on your use cases for what exceptions apply.

As for the other two ideas, ignore-hidden is happening at a completely different level and is unlikely to change.

I think it should also ignore vcs dirs. I need to check why it isn't.

**Comment by kachick** [comment]
Thank you for sharing it with me!

I'll consider using arguments with `shell aliasing`/`task runner` and using the GitHub Action's `files` input 🙇‍♂️
