### ISSUE TITLE
I know the correction for sure

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#781]
```
`Trailling` -> `Trailing`, `Trialling`, `Trilling`
```

"Trailling" is for sure the typo of "Trailing".
How can I configure typos to fix it right away?

**Comment by epage** [comment]
[extend-words](https://github.com/crate-ci/typos/blob/master/docs/reference.md) in the config can extend the available corrections used

**Comment by szepeviktor** [comment]
You are right!!


After adding
```toml
[default.extend-words]
"trailling" = "trailing"
```

The fix is a one way
```
error: `Trailling` should be `trailing`
```

Thank you.

**Comment by szepeviktor** [comment]
Oh no!
"Trailling" lost its capital, got turned into "trailing".
```diff
- public function noErrorOnTraillingSemicolonAndWhitespace(Connection $connection)
+ public function noErrorOntrailingSemicolonAndWhitespace(Connection $connection)
```

**Comment by szepeviktor** [comment]
If there are many versions of this typo, what version Should I add?
```toml
"trailling" = "trailing"
#
"Trailling" = "Trailing"
``
