### ISSUE TITLE
Ordinal number after underscore causes it to be marked as typo

### ISSUE THREAD

**Issue by aethiopicuschan** [crate-ci/typos#805]
```sh
$ typos --version
typos-cli 1.16.5
# It's OK
$ echo "foo-2nd" | typos -
# If you use snake_case, typos raises error
$ echo "foo_2nd" | typos -
error: `nd` should be `and`
  --> -:1:6
  |
1 | foo_2nd
  |      ^^
  |
```

Issues that may be relevant: #409

**Comment by aethiopicuschan** [comment]
By adding the regular expression `'[0-9]+(st|nd|rd|th)'` to `default.extend-ignore-re`, I was able to ignore this error. However, I think this is just a workaround, not a fundamental solution. Is there no way to handle it properly without requiring special configurations?

**Comment by epage** [comment]
#409 is meant to deal with markdown.  #466 is for general markdown dealings.  Closing in favor of that
