### ISSUE TITLE
Exclude file with CLI arguments

### ISSUE THREAD

**Issue by howjmay** [crate-ci/typos#813]

**Comment by epage** [comment]
Could you give a use case?

One of the principles in CLI vs config used in `typos` is that `typos` is meant to be used on a project and anything tied to the project should be in the configuration file.  This would generally include excludes.

**Comment by howjmay** [comment]
I would run typos as a CLI tool to examine some project which not owned by me. In this scenario, I can't add a configure file for it

**Comment by szepeviktor** [comment]
Isn't it `typos --exclude="dist"`?

**Comment by howjmay** [comment]
oh shit my bad
