### ISSUE TITLE
Regression on arguement

### ISSUE THREAD

**Issue by WalterSmuts** [crate-ci/typos#816]
I've noticed that the word "arguement" was correctly corrected by the ci at `crate-ci/typos@v1.0.4`:
```
error: `arguement` should be `argument`
```

 and incorrectly ~~corrected~~ ignored by my installation of `typos-cli`:
```
$ typos --version
typos-cli 1.16.8
```

Since I'm on the latest release of `typos-cli` I assume this is a regression since `crate-ci/typos@v1.0.4`. I've checked `crate-ci/typos@master` and it also contains the regression.

**Comment by WalterSmuts** [comment]
Did a `git bisect` and found the regression introduced here:
```
commit 70fbd63b005039cb1053aaa16025207f625f3430 (HEAD, tag: first-bad-commit)
Author: Ed Page <eopage@gmail.com>
Date:   Tue Jul 27 14:20:52 2021 -0500

    fix: Update dictionary

```
Looks like it was intentional:
```bash
$ git show first-bad-commit | grep arguement
-        &["arguement"],
-        &["arguement"],
         &["arguement"],
-        &["arguement"],
         &["arguement"],
-        &["arguement"],
-        &["arguement"],
-    values: &[&["arguement"]],
-        &["arguement"],
```

**Comment by epage** [comment]
Unsure why the dictionary update was delayed to that commit but the root cause is 41048d15b38967b6fd437f263fc858b4b79e3680 because we have some typos in our corrections, we therefore removed them from being typos.
