### ISSUE TITLE
Some false positives and false negatives

### ISSUE THREAD

**Issue by WalterSmuts** [crate-ci/typos#818]
Found some false positives and false negatives:

False positive
```
frontiers -> fromtier
```

False negative
```
projeciton
```

**Comment by epage** [comment]
For the false negative, unless its urgent somehow, please report it at #784.

**Comment by epage** [comment]
```
frontiers -> fromtier
```
I'm not seeing this as being a word we correct.  What version are you running with?

**Comment by WalterSmuts** [comment]
Apologies, I just figured out it was a search and replace on my side (`fron -> from`). I should've double-checked before I submitted.
