### ISSUE TITLE
[ SUGGESTION ] - remove version from release filename

### ISSUE THREAD

**Issue by mrjackwills** [crate-ci/typos#845]
I'm not entirely sure what the current best practice is, I see different projects doing various different things, and this problem may only effect me and my personal workflows.

But, my issue is that currently typos is released with a file name such as `
typos-v1.16.16-x86_64-unknown-linux-musl.tar.gz `

I used typos in Docker devcontainers, and like to use a single-liner to download, however I need constantly know the most up-to-date version in order to download (via the Github latest url) , e.g.

`wget https://www.github.com/crate-cli/typos/releases/latest/download/typos-v1.16.16-x86_64-unknown-linux-musl.tar.gz`

Whereas, if the version was removed from the file name, I could download more easily with the simple

`wget https://www.github.com/crate-cli/typos/releases/latest/download/typos-x86_64-unknown-linux-musl.tar.gz`

Am I missing something obvious and/or important?

If people want to download a specific version, they are (and would) still able to, by for example using this url

`https://github.com/crate-ci/typos/releases/download/v1.16.13/typos[-v1.16.13]-x86_64-unknown-linux-musl.tar.gz`

**Comment by epage** [comment]
This is to be compatible with [gh-install](https://github.com/crate-ci/gh-install) which is a pattern carried over from [trust](https://github.com/japaric/trust/)

Unsure what the original motivation for it was but it looks like other projects, like [ripgrep](https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0) do this.

I know for myself, I sometimes end up with multiple versions of these files in my `Downloads/` and having the version is more informative than `(1)` suffixes.

**Comment by epage** [comment]
Yes, that is basically what `gh-install` does
