### ISSUE TITLE
`--format json` does not produce valid json

### ISSUE THREAD

**Issue by LilithHafner** [crate-ci/typos#853]
`typos --format json >> file.json` gives a newline delimited list of json objects. This is not valid json. It is, however, valid [json lines](https://jsonlines.org/). It would be good to either emit valid json or clearly document that the output is not valid json (e.g. rename `--format json` to `--format jsonl`)

**Comment by epage** [comment]
Other tools do that as well, like `cargo check --message-format json`.  Granted, that has an explicit qualifier that its for each message but typos is effectively as well, just shorter.
