### ISSUE TITLE
Difference between shown errors and json format

### ISSUE THREAD

**Issue by MrMuetze** [crate-ci/typos#858]
Hi everyone :)
We are currently introducing `typos` to our CI and we noticed that there is a difference between the messages shown after running typos with `typos` and the messages included in the JSON after running `typos --format json`.

```
gst % typos
error: `seperate` should be `separate`
  --> ./gst-writers/src/gdal_based/merged_shapefile.rs:99:25
   |
99 |     // needs to be in a seperate function or at least it needs to be scoped,
   |                         ^^^^^^^^
   |
```
vs
```
gst % typos --format json
{"type":"typo","path":"./gst-writers/src/gdal_based/merged_shapefile.rs","line_num":99,"byte_offset":24,"typo":"seperate","corrections":["separate"]}
{"type":"binary_file","path":"./gst-writers/src/gltf/tiles3d/snapshots/gst_writers__gltf__tiles3d__tests__write_valid_tin_equatorial.snap"}
```
Is that something to be expected or could this be a bug that causes this?

Let me know if I can provide additional information!

**Comment by epage** [comment]
I assume you are referring to the reporting that a binary file is present?  We don't report messages like that with the normal format as it can get a bit noisy but for programmatic output we wanted to be more complete.

**Comment by MrMuetze** [comment]
Ah I understand. So this line only indicates that a binary file is present and not that any issues are detected with it I assume?

**Comment by epage** [comment]
It is saying that a file is present that it could not check.
