### ISSUE TITLE
Stop checking the configuration file

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#860]
`typos -c ./.github/workflows/typo_config.toml`

Usually config files are full of typos.
Please consider ignoring specified config files.

**Comment by epage** [comment]
#711 had this for auto-discovered configs which was fixed in #762.  We did this all by checkin for the built-in file names.  We are not checking for the actual active config file name.

**Comment by epage** [comment]
Should we bother fixing this or just have people name their `--config` file to be one of the built-in names?

**Comment by szepeviktor** [comment]
> to be one of the built-in names?

I second this.

**Comment by Aakarsh1024** [comment]
Hi, I'm new and I'd like to work on this. Can I please take it?
