### ISSUE TITLE
Support a dedicated `.typosignore` file

### ISSUE THREAD

**Issue by dmoklaf** [crate-ci/typos#867]
My understanding from the documentation and the code is that `.ignore` or `.gitignore` files can be taken into account by `typos`. However these files may carry some meaning for other tools and utilities, having them ignore the same files.

In my case I want only to declare ignored files for typos and not for other tools.

This could be possible with dedicated `.typosignore` files

**Comment by epage** [comment]
Is there a reason [`files.extend-exclude`](https://github.com/crate-ci/typos/blob/master/docs/reference.md) wouldn't work for your case?

**Comment by dmoklaf** [comment]
We needed a decentralized ignore file (i.e., that can be splitted within various projects and directories), and I didn't notice that the typos.toml file itself could be decentralized in the various directories (instead of being forced to be unique). So you are suggesting, if I understand correctly, to use the typos.toml file as a .ignore file, by placing it in the various places where I need to ignore some specific typos. This is a great solution. It was not obvious at first sight to me (this is much more powerful that what most tools propose).

**Comment by epage** [comment]
Layered configs are tracked in #193. There hasn't been much interest expressed in them so far.  Might be good to comment on your use case for why it needs to be distributed.

Closing in favor of #193.
