### ISSUE TITLE
Change in `extend-exclude` behavior

### ISSUE THREAD

**Issue by zanieb** [crate-ci/typos#868]
Upgrading from `v1.14.12` to `v1.16.22` I'm encountering a typo detected in a file which should be excluded.

With the configuration:

```toml
[files]
extend-exclude = ["resources", "snapshots"]
```

The file `crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__match_cases.snap` has a fixed typo.

You can reproduce this with `pre-commit run --all-files` in https://github.com/astral-sh/ruff with the bumped version.

Changing to `"**/snapshots/**/*"` resolves this.

Please let me know if you need more information or if this is expected. I can produce a smaller example if necessary.

**Comment by epage** [comment]
I'm assuming this was broken by #837 (had worried there was a corner case like this).  I have a local reproduction case.

The odd thing is that I would assume the `exclude` key in your pre-commit hook would prevent this from being hit.

**Comment by zanieb** [comment]
Thanks for the fast fix. Gosh who knows what's up with the `pre-commit` hook exclude, guess that's the next thing to investigate.
