### ISSUE TITLE
Benefit from Wikipedia's RegExTypoFix

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#870]
Maybe typos can be better by using some of these.

for humans: https://en.wikipedia.org/wiki/Wikipedia:AutoWikiBrowser/Typos
for machines: https://en.wikipedia.org/wiki/Wikipedia:AutoWikiBrowser/Typos?action=raw

**Comment by epage** [comment]
I'm having a hard time seeing how we could leverage this as we have the following limitations
- Single-word corrections
- Performance (making using regex in the hot loop a non-starter)

There might be a way to use some regex expansion tools to filter out the multi-word stuff and to make it a hard coded list but that seems like a lot of work for uncertain gains.

**Comment by szepeviktor** [comment]
👍🏻 for regex expansion tools and uncertain gains.
