### ISSUE TITLE
`CHECK` interpreted as `CHEC`

### ISSUE THREAD

**Issue by rikhuijzer** [crate-ci/typos#874]
When I create an empty folder and add one file containing:
```text
script will attempt to insert the generated CHECKs to the source file by looking
```
then `typos` will return:
```
error: `CHEC` should be `CHECK`
  --> ./tmp.txt:1:45
  |
1 | script will attempt to insert the generated CHECKs to the source file by looking
  |                                             ^^^^
  |
```
Is this a false-positive or am I doing something wrong?

**Comment by epage** [comment]
If you run `typos --words` you'll see that `CHECKs` is being split into `CHEC Ks` as `Ks` is being assumed to be a camel case name.

**Comment by epage** [comment]
Closing in favor of #745
