### ISSUE TITLE
Bad case when used with cert

### ISSUE THREAD

**Issue by j2gg0s** [crate-ci/typos#883]
```
error: `TEH` should be `THE`
  --> ./pilot/pkg/model/jwks_resolver.go:316:174
    |
316 |       "p": "7EK8xaN7qCdWCeQ1ptXWvuc6qotZc6oD-j1ecgel9FqmfkmaioVEbEAfP_N73QAjw-sU60sK3XK8LV4fkGUoJV-MDvmiCzy3wUPe-adSaTCxFykgOm6SPA9NKCqAh8lUm6GUm9RZkjwkv4xzZ8pJjng3d74WXx7zhTEH6yi4E00",
    |                                                                                                                                                                              ^^^
    |
```

Can we ignore strings longer than a certain length?

**Comment by epage** [comment]
`typos` has no concept of a string literals as it is programming language agnostic.

Within that string literal, I think the longest segment is 70 characters which it can be reasonable in some ecosystems to have identifiers that are that long or longer (our base64 detection code does not match values that look like <=90 character identifiers).

#484 is about a heuristic for ignoring things that look like identifiers but are garbage while we have #316 for excluding lines.  Closing in favor of those.
