### ISSUE TITLE
Cannot exclude false positive in file names

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#885]
```
error: `olt` should be `old`
  --> ./include/olt-manager.php:1
```

Please help me where to exclude "olt-manager".
It is bad practice to exclude "olt" in `extend-words`.
I'd like to exclude only the false positive in the file name, not its contents.

**Comment by epage** [comment]
As `-` is not considered an identifier separator to use `extend-identifiers`, you can either
- put `olt` in `extend-words` (imo that is finebecause it *is* a word-like within your codebase)
- Use `extend-ignore-re` to ignore arbitrary patterns

**Comment by szepeviktor** [comment]
Thank you. I've tried
```toml
[default]
extend-ignore-re = [
    "olt-manager",
]
```
but it is not ignored.

**Comment by epage** [comment]
Huh, we never did that check for file names.  That is now fixed
