### ISSUE TITLE
Trophy case

### ISSUE THREAD

**Issue by azzamsa** [crate-ci/typos#887]
Hi, 👋

I hope this issue is the right place to express our gratitude since we don't have discussions enabled.
If this annoys any members, please unsubscribe from this non-actionable issue.

Thank you so much for `typos`!  🎖️

**Comment by epage** [comment]
Thanks!

And I hope Discussions are now enabled (Github shows the tab for maintainers even when its not setup, hiding the fact that I need to do a step ... I think)
