### ISSUE TITLE
Wiki: Link to typos-vscode

### ISSUE THREAD

**Issue by peter-kehl** [crate-ci/typos#889]
Please add a link to https://github.com/tekumara/typos-vscode to https://github.com/crate-ci/typos/wiki. (I would have updated it myself, but it's not publicly editable.) Thank you in advance.

**Comment by epage** [comment]
That wiki page is listing projects using typos.  This is an integration for typos and we already have it included in the README: https://github.com/crate-ci/typos#integrations

**Comment by peter-kehl** [comment]
Thank you.
