### ISSUE TITLE
Required libc version

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#903]
```
typos: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by typos)
typos: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by typos)
typos: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by typos)
```
Comment from https://github.com/letsencrypt/boulder/pull/7248#pullrequestreview-1813784028
In an docker container from `buildpack-deps:focal-scm`
https://hub.docker.com/layers/library/buildpack-deps/focal-scm/images/sha256-2f9f349caffb0f2ade36f793a86536457b2d1e90ecf0eae5a47e328cdd0209f5?context=explore

On my computer (old Debian) `ldd` says "statically linked".

Could you help running typos?

**Comment by epage** [comment]
The docker image in that PR is dointg:

> `cargo install typos-cli`

CI is building for `--target x86_64-unknown-linux-musl` to ensure everything is statically linked.

The other option is to make sure your build uses the same version of libc as when you deploy.  Not sure how your process is fully working to say how to make that work.
