### ISSUE TITLE
question: how can make typos check html and rst files in github actions?

### ISSUE THREAD

**Issue by bratpiorka** [crate-ci/typos#904]
How can make typos check html and rst files in github actions?

I see that it doesn't check these extensions by default. I intentionally added typos to html and rst files in my project but the action reports no error. 

Here is my config:

            - name: Run a spell check
              uses: crate-ci/typos@v1.16.23
              with:
                config: ./.github/workflows/.spellcheck-conf.toml

---- 
.spellcheck-conf.toml :

[default]
extend-ignore-words-re = ["ASSER", "Tne"]

**Comment by bratpiorka** [comment]
The files I want to be checked are located in ./scripts folder, so this is not a hidden directory. 
But should I add:

[files]
ignore-hidden = false

to my config?

**Comment by epage** [comment]
Oh, I misunderstood as I thought you were saying they were in the actions directory.

I'd need reproduction steps to figure out what is going wrong.

Some quick triaging:
- Why do you think html and rst files are not checked?
- What typos did you intentionally add?   Typos has a hard coded list of typos (deny list) which is on contrast with spell checkers in text editors which have a dictionary of valid words and call attention to things not in the dictionary (allow list).  You would need to test this out with a typo in our dictionary.

**Comment by bratpiorka** [comment]
Oh I see, thanks .. I thought typos is a typos AND spell-check tool. When I tried to check if it caches "aray" word and it worked well. I guess I had to add additional spell-check action.
