### ISSUE TITLE
Remove tags from release filenames

### ISSUE THREAD

**Issue by Luni-4** [crate-ci/typos#923]
When in our projects we automatically download `typos`, we would like to download the `latest` version without having to specify the tag.

The current URL for the latest version:

`https://github.com/crate-ci/typos/releases/download/v1.18.0/typos-v1.18.0-x86_64-unknown-linux-musl.tar.gz`

Would it be possible to have this one instead: `https://github.com/crate-ci/typos/releases/latest/download/typos-x86_64-unknown-linux-musl.tar.gz`. It is possible to obtain this URL just removing the tag from the filename.

**Comment by epage** [comment]
This looks to be the same as #845, so closing in favor of that.  If you think there is enough cause to re-open that issue, let us know!  Also, if there is a reason this should be kept separate, let us know!
