### ISSUE TITLE
`derivate` isn't in Word List

### ISSUE THREAD

**Issue by cwfitzgerald** [crate-ci/typos#924]
A pretty simple one, was just surprised it wasn't in the word list. `typos` wanted to correct `derivate` (i.e. the nominalization of "to derive") to `derivative`.

Thanks for this awesome tool ([we just started using it in wgpu](https://github.com/gfx-rs/wgpu/pull/5191))!

(I didn't put this in #921, as that only seemed to be for new corrections)

**Comment by epage** [comment]
Thanks for pointing this out!

We added a list of english words to prevent this but somehow this wasn't in the list and I wonder what other words we are missing...
