### ISSUE TITLE
Fix "cancel" as per current locale

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#948]
Currently with default locale "canceled" is a marked as a typo.

> The forms of cancel in American English are typically canceled and canceling; in British English they are cancelled and cancelling. 

https://www.merriam-webster.com/dictionary/cancel

```
en_us -> canceled, canceling
en_gb -> cancelled, cancelling
```

Thank you.

**Comment by szepeviktor** [comment]
But

> There are examples of cancelled in American use, and of canceled in British, so you needn’t feel bad about yourself if you mistakenly use the variant that is less common where you live

https://www.merriam-webster.com/grammar/canceled-or-cancelled

**Comment by epage** [comment]
Sorry for the delay.

You mentioned "default locale".  Without setting a locale, I do not see it corrected.  Alternatively, 10 days before this post, you posted 
https://github.com/crate-ci/typos/issues/943#issuecomment-1991272854

Could you clarify under what conditions you are seeing what behavior?

**Comment by szepeviktor** [comment]
That might be a mistake. Even v1.19.0 allows both version.
