### ISSUE TITLE
OpenGraph metadata identifier detected as a false positive

### ISSUE THREAD

**Issue by zlataovce** [crate-ci/typos#960]
The `1.20.0` release introduced the `og -> of` correction, which flags an identifier of fairly common [OpenGraph metadata](https://ogp.me/).

A practical example of this would be running `typos` on [the source of the OGP site](https://github.com/facebookarchive/open-graph-protocol/blob/master/index.html):
```
error: `og` should be `of`
  --> index.html:3:17
  |
3 |   <head prefix="og: https://ogp.me/ns#">
  |                 ^^
  |
error: `og` should be `of`
  --> index.html:9:21
  |
9 |     <meta property="og:title" content="Open Graph protocol">
  |                     ^^
  |
error: `og` should be `of`
  --> index.html:10:21
   |
10 |     <meta property="og:type" content="website">
   |                     ^^
   |
error: `og` should be `of`
  --> index.html:11:21
   |
11 |     <meta property="og:url" content="https://ogp.me/">
   |                     ^^
   |

<truncated>
```

**Comment by epage** [comment]
What I'm trying to understand with this is how prevalent this is if it should be something built-in or worked around on the users side.

**Comment by zlataovce** [comment]
searching for `og:title` (example) on GitHub yields [several million results](https://github.com/search?q=og%3Atitle&type=code) - developers often use such metadata to make their websites more appealing to search engines and in social media embeds

**Comment by epage** [comment]
Having almost no background in the web, this appeared to be yet another attempt at RDF that seemed doomed.  I didn't realize this is what empowers the previews within social media sites.  That does seem fairly prevalent and makes sense to not get in the way of.
