### ISSUE TITLE
Various false positives since 1.20

### ISSUE THREAD

**Issue by groengpx** [crate-ci/typos#970]
- `IIS` is corrected to `IS` (IIS is the webserver from Microsoft)
- `iot` is corrected to `it` (iot is short for internet of things)

Also, I found a few aggressive corrections. These corrections are probably fine, but I will list them nonetheless:
- `ang` is corrected to `and` (I used it as short for `angle`, but I probably should not short it.)
- `dur` is corrected to `due` (I used it as short for duration).

**Comment by epage** [comment]
Looking around, `ang` and `dur` seem like common enough abbreviations to include

**Comment by RudolfMan** [comment]
After upgrade to 1.20.0 Our pipeline started also failing on 
 - `hd` - in JWT it's a claim name for "host domain"
 - `ws` - from Postgres `CONCAT_WS` to concatenate strings **w**ith a **s**eparator
 - `ein` - Employer Identification Number

**Comment by epage** [comment]
Its better to post to new issues rather than
- Posting to closed issues
- Posting to issues on separate topics

btw `ws` was tracked in #963
