### ISSUE TITLE
`lst` could also mean "list"

### ISSUE THREAD

**Issue by qartik** [crate-ci/typos#974]
`lst` is a common abbreviation for `list` that tends to be a keyword in many languages, it is incorrect to change it to "last" as done in #955.

**Comment by epage** [comment]
As the requests for more abbreviations come in, I've been trying to come up with principles to decide what abbreviations get officially recognized and which we should.

In this case, I wonder if we should limit `lst` to the Python file type.

**Comment by qartik** [comment]
I think that's fine.
