### ISSUE TITLE
`Automations` false positive

### ISSUE THREAD

**Issue by alexfertel** [crate-ci/typos#979]
I got this today, which I believe is a false positive. As you can see, the sentence wouldn't make sense if we changed it to `Automation`.

![image](https://github.com/crate-ci/typos/assets/22298999/15c49a11-f07b-4a95-a0b8-8ab14971cb43)

**Comment by epage** [comment]
> The noun automation can be countable or uncountable.
>
> In more general, commonly used, contexts, the plural form will also be [automation](https://www.wordhippo.com/what-is/the-meaning-of-the-word/automation.html).
>
> However, in more specific contexts, the plural form can also be [automations](https://www.wordhippo.com/what-is/the-meaning-of-the-word/automations.html) e.g. in reference to various types of automations or a collection of automations.

https://www.wordhippo.com/what-is/the-plural-of/automation.html

**Comment by alexfertel** [comment]
Sorry, do you have any thoughts or questions? Unsure what you meant with the comment 😅

**Comment by cnpryer** [comment]
> Sorry, do you have any thoughts or questions? Unsure what you meant with the comment 😅

It's grammatically incorrect to use the word *automations*. I guess except in specific contexts (given the last part of the quoted text). So spell checkers will pick it up as incorrect spelling of *automation*.

With that said, FWIW I do often have to put this in my _typos.toml files now. So I'd wonder if as a variable name the context is appropriate.
```toml
[default.extend-words]
"equipments" = "equipments"
```

Correcting plural forms of nouns seems a little strict for a *source code spell checker*, but I guess there has to be a tradeoff somewhere.

I often name my *things* that are iterable or composed of many *things* as the plural form -- regardless of if  it ends up grammatically correct.

A simple example is how this is used in a for loop.

```py
for equipment in equipments:
    ...
```
