### ISSUE TITLE
False positive caused by `HD`

### ISSUE THREAD

**Issue by DeadNews** [crate-ci/typos#987]
## `HD` should be `HAD`

Example: https://github.com/DeadNews/shell-scripts/pull/25/commits/ea9d63cb3757c1d0318cefb414e6d1731dbe6858

`HD` is a common abbreviation.

https://en.wikipedia.org/wiki/HD#Technology
https://grep.app/search?q=hd&words=true

<details>

## `thr` should be `the`

Example: https://github.com/DeadNews/dnfunc/pull/147/commits/e0a7db6ba62f0a6ce95c090473fc1b9bf48b8d6c

`thr` is a common abbreviation for `threshold`.

https://grep.app/search?q=thr&words=true

</details>

----

I wonder if it is even worth fixing 2-3 letter sequences? 
The chance of false positives is very high. 
Is it possible to ignore all 2-3 letter sequences via regex in the settings?

**Comment by epage** [comment]
Please do not mix issues as the discussion and resolution of each can be independent.

I am adjusting this to be about `HD`.  Feel free to make a new issue about `thr`
