### ISSUE TITLE
False positive: inout

### ISSUE THREAD

**Issue by svix-jplatte** [crate-ci/typos#991]
"inout" is a pretty common abbreviation for "input/output", used for example in [Rust inline assembly](https://doc.rust-lang.org/nightly/reference/inline-assembly.html), [Swift functions](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/functions/#In-Out-Parameters) and MySQL / [MariaDB functions](https://mariadb.com/kb/en/create-function/#in-out-inout-in-out).

**Comment by svix-jplatte** [comment]
I came across it in a C codebase, so I'd be in favor of not detecting it as a typo anywhere.

**Comment by epage** [comment]
Beyond what is officially supported, the challenge is to determine what conventions people use should be officially adopted.  With the recent batch of additions, we've been hitting a lot of those and its been getting a lot murkier to decide what should be built-in and what should be left to each code base to deal with.

However, I think I'm going to let this one in.

**Comment by svix-jplatte** [comment]
Thanks!
