### ISSUE TITLE
False positive caused by `km`

### ISSUE THREAD

**Issue by officel** [crate-ci/typos#993]
`km` should be `kms`

maybe?
https://github.com/crate-ci/typos/issues/955

`kms` is a aws service name.

**Comment by officel** [comment]
```
$ pre-commit run typos --all-files                                                          
typos....................................................................Failed
- hook id: typos
- files were modified by this hook
$ git st
## HEAD (no branch)
M  .pre-commit-config.yaml
 D terraform/aws/module_kms/aws_kms_default.tf
?? terraform/aws/module_kms/aws_km_default.tf
```

It seems to rename the file.
The strings inside are not changed.

**Comment by epage** [comment]
Going to go ahead and change this as this seems to be a cross-company acronym.  I am hesitant in general though of including product-specific acronyms and abbreviations as that is a bit of a can of worms of what to cover or not.

**Comment by officel** [comment]
Agreed.
I think very difficult decisions need to be made.
I don't speak English, so I don't know how hard it will be, but I am hopeful that we can make just the right decision.

Thank you.
